### ISSUE TITLE
Session can not be restored when using flutter web

### ISSUE THREAD

**Issue by c0ball** [supabase/supabase-flutter#802] opened 2024-01-18 21:26 UTC
I am facing the issue, that when I am building my flutter app for the web, deploying it to a web server and running it for the first time, everything works as expected. I can log into my supabase backend, my token gets stored in the local storage and I can use my app as usual. 
But as soon as I reload the page, the website won't load and stays stuck during the initialization of supabase auth (_See screenshot for more information_). 

To fix this issue, I have to clear the browser data for the webpage. 

Thanks in advance for your help.

**Screenshots**
<img width="816" alt="grafik" src="https://github.com/supabase/supabase-flutter/assets/41505593/c112ade8-615f-4120-9628-27facd009c4a">

**Version:**
├── supabase_flutter 2.2.0
│   ├── supabase 2.0.4
│   │   ├── functions_client 2.0.0
│   │   ├── gotrue 2.3.0
│   │   ├── postgrest 2.1.0
│   │   ├── realtime_client 2.0.0
│   │   ├── storage_client 2.0.0

**Comment by dshukertjr** [comment] 2024-01-19 00:07
@c0ball 
This is happening on Google Chrome, correct?

We had an issue where Supabase initialization stopped on safari with dev tools open, but I couldn't reproduce the issue on Chrome. https://github.com/supabase/supabase-flutter/issues/794

**Comment by dshukertjr** [comment] 2024-01-19 00:19
Yeah, I cannot seem to be able to reproduce the issue. Would you be able to provide a step-by-step of how you are running your app?

**Comment by c0ball** [comment] 2024-01-19 07:50
Thanks for the quick reply,
I was able to reproduce this issue on Safari, Firefox, and Chrome with the Dev Tools opened and closed, so I do not think that this was related to a specific browser or the dev tools.

I do not know what's has changed over the night, because this issue was bothering me for weeks, but since this morning I am unable to reproduce this issue on any of the browsers. The build is exactly the same as yesterday, when this issue last occurred to me. I tried changing the access token expiry time to check whether this has any influence, but it does not. I am unable to reproduce this issue. I also tried the same procedure with the latest 2.3.0 version of supabase_flutter, also without any issues.

The only thing I could think of is a change on supabases side, as I am using their SaaS service. Could this be possible? 

Thanks for your help, and I will let you know if I can reproduce the error again.

**Comment by dshukertjr** [comment] 2024-01-19 08:00
That is very interesting. As far as I know, there hasn't been any change on the Supabase side that I could think of that could affect this, but it is a weird issue, so who knows? 

I'm going to close this issue for now, but if you ever run into the same issue again, please do not hesitate to report it!

**Closed by dshukertjr** 2024-01-19 08:00 UTC
Labels: bug
