### ISSUE TITLE
Widget closes when signing in using Supabase

### ISSUE THREAD

**Issue by Louis-Wave** [supabase/supabase-flutter#940] opened 2024-05-30 00:25 UTC
**Describe the bug**

I'm working on a Flutter project.
When I call the login dialog on my main page and sign in, context.pop(); Even if there is no code like , the dialog will be closed.

**To Reproduce**

Enter email and password in each of the two textControllers and sign in using the following code.

Supabase.instance.client.auth.signInWithPassword(email: _model.textController1.text,password: _model.textController2.text);

**Expected behavior**

There should be no change on the screen.

**Screenshots**

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

supabase_flutter: ^2.5.2

**Additional context**

**Comment by dshukertjr** [comment] 2024-05-30 17:00
Hi there,

The supabase_flutter library does not interfere with your UI, and the cause of your dialog closing is in the code you wrote.

**Closed by dshukertjr** 2024-05-30 17:00 UTC
Labels: bug, auth
