### ISSUE TITLE
signOut() not working

### ISSUE THREAD

**Issue by Faizan-Pasha** [supabase/supabase-flutter#344] opened 2023-02-04 20:56 UTC
**Describe the bug**
Supabase flutter signOut() is not removing the session or the user from the device.

**To Reproduce**
1. Follow Flutter [QuickStart Tutorial](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter)
2. SignOut()
3. See error

**Expected behavior**
Afer Signing Out the token still stays in the app

**Version (please complete the following information):**
 - 1.3.1

**Comment by Vinzent03** [comment] 2023-02-05 11:39
Please share more information with us to help you:
- code of your sign-out
- what error do you encounter? Just the fact of an error doesn't help us.
- what do you mean with "the token still stays in the app"

**Comment by dshukertjr** [comment] 2023-02-05 15:55
Closing as a duplicate of https://github.com/supabase/supabase-flutter/issues/245.

@Faizan-Pasha 
You can read the comment [here](https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807) for more details, but the session is persisted in the deep link, and you need to do a full restart of your debugging session in order to remove the persisted deep link that is causing the issue.

**Closed by dshukertjr** 2023-02-05 15:55 UTC
Labels: bug
