### ISSUE TITLE
No access_token detected (orj. example)

### ISSUE THREAD

**Issue by yutech23** [supabase/supabase-flutter#274] opened 2022-11-12 00:01 UTC
I USE autH.signInWithPassword() 

I upgraded 1.1.0 version. I got a error. it's "No access_token detected. 
I have tried  example in git but I got same error. 
Please Help can

![image](https://user-images.githubusercontent.com/42283661/201445929-dcce2e81-3e2f-4f75-8683-0895cb738e79.png)

**Comment by dshukertjr** [comment] 2022-11-12 02:32
@yutech23 Could you follow the issue format and provide steps to reproduce?

**Comment by d-e-h-i-o** [comment] 2022-11-15 21:39
@dshukertjr I'm getting the same error as well. To reproduce just use the [official example](https://github.com/supabase/supabase/tree/master/examples/user-management/flutter-user-management), bump supabase_flutter to ^1.0.1 and open the app in a webbrowser.

It would be great if you could investigate that bug.

**Comment by d-e-h-i-o** [comment] 2022-11-15 21:46
Some more info: In my own codebase, I also get the error in version 1.0.1. It basically follows the tutorial from the [supabase website](https://supabase.com/docs/guides/with-flutter#set-up-a-login-page). When I go to my splash page `http://localhost:63771/#SplashPage` it works flawless, however, everytime I reload from a different screen, e.g. `http://localhost:63771/#LearningTab` the error occurs.

``***** SupabaseDeepLinkingMixin startAuthObserver     
***** SupabaseAuthState handleDeeplink http://localhost:63771/#LearningTab   
onReceivedAuthDeeplink uri: http://localhost:63771/#LearningTab   
No access_token detected.   
``
I hope that helps.

**Comment by d-e-h-i-o** [comment] 2022-11-15 21:51
@yutech23 Configuring [URL strategy](https://docs.flutter.dev/development/ui/navigation/url-strategies) to `usePathUrlStrategy()` helped me, if you are looking for a quick fix.

**Comment by dshukertjr** [comment] 2022-11-17 03:22
@d-e-h-i-o 
I just tried the example app you mentioned, and was able to sign in without any issue. 
https://www.loom.com/share/913ceb26e8294ab3a1a80330b518a6b6

>however, every time I reload from a different screen, e.g. http://localhost:63771/#LearningTab the error occurs.

What is the use case here? This example app is configured so that the user has to go through SplashPage in order to be redirected to the appropriate page.

**Comment by yutech23** [comment] 2022-11-18 13:45
> @yutech23 Configuring [URL strategy](https://docs.flutter.dev/development/ui/navigation/url-strategies) to `usePathUrlStrategy()` helped me, if you are looking for a quick fix.

it doesn't work. :(

**Comment by dshukertjr** [comment] 2022-11-19 04:12
@yutech23 
What happens after you click the confirmation link on your email? Does it not open the account page?

**Comment by yutech23** [comment] 2022-11-19 08:10
> @yutech23 What happens after you click the confirmation link on your email? Does it not open the account page like in the video [here](https://github.com/supabase/supabase-flutter/issues/274#issuecomment-1318007793)?

I don't use email's confirmation. I use signInWithPassword() func.  It gives an error right after running the application.


**************Database Connection Code******************
//Giriş Ekran Sorgulama
  Future<Map<String, String?>> singIn(
      BuildContext context, String setEmail, String setPassword) async {
    Map<String, String?> userSessionMap = {};
    bool status = false;

    try {
      final res = await db.supabase.auth
          .signInWithPassword(email: setEmail, password: setPassword);
      status = true;
      userSessionMap.addAll({
        'id': res.user?.id,
        'token': res.session?.accessToken,
        'refreshToken': res.session?.refreshToken,
        'status': status.toString()
      });
      context.extenionShowSnackBar(message: 'Giriş başarılı.');
      return userSessionMap;
    } on AuthException catch (error) {
      context.extensionShowErrorSnackBar(message: error.message);
      return userSessionMap;
    }
  }

****************** Login Screen Code (Button Action)********************
 //Kayıt Buttonu
  DecoratedBox widgetButtonSaveOn(BuildContext context) {
    return DecoratedBox(
        decoration: context.extensionThemaButton(),
        child: ElevatedButton(
            focusNode: _loginButtonFocus,
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.transparent,
              disabledBackgroundColor: Colors.transparent,
              shadowColor: Colors.transparent,
            ),
            onPressed: () {
              Kullanici loginKullanici = Kullanici.session();
              db
                  .singIn(context, _controllerEmail.text, _controllerSifre.text)
                  .then((value) {
                if (value['status'] == 'true') {
                  loginKullanici.id = value['id']!;
                  loginKullanici.token = value['token'];
                  loginKullanici.refreshToken = value['refreshToken'];
                
                } else {
                  _controllerSifre.clear();
                }
              });
            },


******************Main********************
Future<void> main() async {
  usePathUrlStrategy();
  DbHelper.dbBaslat();
  runApp(const MyApp());
}

**Comment by TommyLCox** [comment] 2022-11-21 16:05
> @yutech23 Could you follow the issue format and provide steps to reproduce?

I was trying to setup a basic app to demonstrate this error that I am also seeing. I could not even accomplish that due to to another similar error in the basic web demo project (error is under flutter web only) that I posted here - #282 . If I can get #282 resolved, I will continue to work to setup a basic project to confirm the error that @yutech23  is having.

**Comment by yutech23** [comment] 2022-11-21 22:28
> @yutech23 I think I finally understand what the issue is here. `No access_token detected` is an error message from the deep link handler, that is just saying there were no access token in the current URL when you launch an app, which is expected. I think we can better handle the case, and not make it seem like there is something wrong with the code, but this should not have any effects on your app's functionalities.
i had guessed. :) Do we have the solution ? :) Because;
when running (F5 key) application with vscode, Application stops. But when running application with terminal, Application continues. just showing error in terminal screen. so I can't update new version. :(

**Comment by yutech23** [comment] 2022-11-21 22:29
> @yutech23 I think I finally understand what the issue is here. `No access_token detected` is an error message from the deep link handler, that is just saying there were no access token in the current URL when you launch an app, which is expected. I think we can better handle the case, and not make it seem like there is something wrong with the code, but this should not have any effects on your app's functionalities.

i had guessed. :) Do we have the solution ? :) Because;
when running (F5 key) application with vscode, Application stops. But when running application with terminal, Application continues. just showing error in terminal screen. so I can't update new version

**Comment by TommyLCox** [comment] 2022-11-21 22:33
> @yutech23 I think I finally understand what the issue is here. `No access_token detected` is an error message from the deep link handler, that is just saying there were no access token in the current URL when you launch an app, which is expected. I think we can better handle the case, and not make it seem like there is something wrong with the code, but this should not have any effects on your app's functionalities.

@dshukertjr  - Yes, I was coming on here to let you know that it was in the deep link handler:
`***** Supabase init completed Instance of 'Supabase'
Got object store box in database supabase_authentication.
***** SupabaseDeepLinkingMixin startAuthObserver
***** SupabaseAuthState handleDeeplink http://localhost:49855/#/
onReceivedAuthDeeplink uri: http://localhost:49855/#/
No access_token detected.`

I agree that it "should not" cause downstream effects on an app's functionality, but it is confusing because it produces  a lot of messages that say "Error" and outputs an error stack trace that makes it appear worse than what it is. Also, it is an Unhandled Exception and there is no real way to catch it.

Suggestion: Just make it an informational message "No access token found" and don't throw an unhandled exception all the way out to the application.

**Comment by dshukertjr** [comment] 2022-11-22 07:58
@yutech23 
You can also just press the play button on your vs code debug controller. 
<img width="403" alt="Screen Shot 2022-11-22 at 16 57 29" src="https://user-images.githubusercontent.com/18113850/203257478-b15f7b71-e8fa-4427-85aa-4c1eab15ce75.png">

**Comment by dshukertjr** [comment] 2022-11-22 08:12
@TommyLCox 
Yup, agree that this error is confusing. I was taking a look at the code, and the cause is that parsing the URL is occurring for every URL of the page, where as it should only be parsed if there are certain query parameters present, like accessToken. Will try to ship a fix for this one soon!

**Comment by yutech23** [comment] 2022-11-22 10:41
> @yutech23 You can also just press the play button on your vs code debug controller. <img alt="Screen Shot 2022-11-22 at 16 57 29" width="403" src="https://user-images.githubusercontent.com/18113850/203257478-b15f7b71-e8fa-4427-85aa-4c1eab15ce75.png">

Thank you for all reply. I am waiting new update.

**Comment by d-e-h-i-o** [comment] 2022-11-22 12:06
> @d-e-h-i-o I just tried the example app you mentioned, and was able to sign in without any issue. https://www.loom.com/share/913ceb26e8294ab3a1a80330b518a6b6
> 
> > however, every time I reload from a different screen, e.g. http://localhost:63771/#LearningTab the error occurs.
> 
> What is the use case here? This example app is configured so that the user has to go through SplashPage in order to be redirected to the appropriate page.

@dshukertjr I'm sorry, I should have specified that you need to look at the console to see the error message at the example app. For my app, there was no specific use case (except that people do refresh a browser sometimes, and staying at a route would maybe be a better user experience). 

Thank you very much for looking into it!

**Closed** 2022-11-24 02:58 UTC
Labels: bug

**Comment by dshukertjr** [comment] 2022-11-24 10:08
Sorry for the delay, but this issue should now be fixed with [v1.2.1 of supabase-flutter](https://pub.dev/packages/supabase_flutter)!

**Comment by yutech23** [comment] 2022-11-24 14:25
> Sorry for the delay, but this issue should now be fixed with [v1.2.1 of supabase-flutter](https://pub.dev/packages/supabase_flutter)!

Thank you @dshukertjr :) i will try right away.
