### ISSUE TITLE
Sentry reports AuthRetryableFetchError

### ISSUE THREAD

**Issue by RCVZ** [supabase/supabase-flutter#929] opened 2024-05-14 11:08 UTC
**Describe the bug**
Sentry reports a couple of AuthRetryableFetchError
All of the reports are on iOS(But those are like 99% of my users)

**To Reproduce**
I have not been able to reproduce this with one of my own devices.

**Version:**
supabase_flutter 2.5.2
supabase 2.1.2
functions_client 2.1.0
gotrue 2.6.1
postgrest 2.1.1
realtime_client 2.0.4
storage_client 2.0.1

**Additional context**
```
AuthException(message: Invalid Refresh Token: Refresh Token Not Found, statusCode: 400)
  App                 0x10bb1abd4  GoTrueClient.notifyException (gotrue_client.dart:1206)
  App                 0x10bd5c604  GoTrueClient.recoverSession (gotrue_client.dart:995)
  File "<asynchronous suspension>"
  App                 0x10bd5c32c  SupabaseAuth.recoverSession (supabase_auth.dart:90)
  File "<asynchronous suspension>"
  App                 0x10bb1aa3c  CancelableCompleter.complete.<T> (cancelable_operation.dart:427)
 ```

**Comment by dshukertjr** [comment] 2024-05-14 12:34
Closing this as a duplicate of https://github.com/supabase/supabase-flutter/issues/928

**Closed by dshukertjr** 2024-05-14 12:34 UTC
Labels: bug, auth
