### ISSUE TITLE
Fetching data in v1.0.1 significnatly slower on debug mode

### ISSUE THREAD

**Issue by avalanche-tm** [supabase/supabase-flutter#264] opened 2022-11-02 10:16 UTC
What is described here happens on the local instance:

I don't have any code to demonstrate this but what I see happening is that requests take 10-20 seconds to execute which definitely wasn't the case in v0.3.3. It doesn't happen always, but it happens most of the time. I realized it takes at least 10 sec for request to even appear in the log of supabase_kong docker container, after which it also takes around 5-10 more seconds for data to actually appear on the screen in Flutter.

Nothing else changed in my codebase except version of flutter_supabase was upgraded from v.0.3.3 to v1.0.1

**Comment by Vinzent03** [comment] 2022-11-02 10:22
@dshukertjr This may be again the isolates. I think we should remove them for now.

**Comment by ofekd** [comment] 2022-11-18 18:17
I'm seeing the same issue, which leads to a terrible development experience

**Comment by avalanche-tm** [comment] 2022-11-19 11:58
> I'm seeing the same issue, which leads to a terrible development experience

Yeah, it's really annoying. Any update on this? Is this planned to be fixed in the next release? @Vinzent03

**Comment by dshukertjr** [comment] 2022-11-20 13:15
Closing as duplicate of https://github.com/supabase/supabase-flutter/issues/229

**Closed by dshukertjr** 2022-11-20 13:15 UTC
Labels: bug
