### ISSUE TITLE
SocketException with "No address associated with hostname" error message when launching the app without `force_staggered_ipv6_lookup` flag

### ISSUE THREAD

**Issue by bangzaka** [supabase/supabase-flutter#814] opened 2024-01-29 12:01 UTC
Exception has occurred.
SocketException (SocketException: Failed host lookup: 'xxxxxxxxxxxxx.supabase.co' (OS Error: No address associated with hostname, errno = 7))

when running vscode debugging, but when using the command:

flutter run --dart-define=dart.library.io.force_staggered_ipv6_lookup=true

This is working normally, can anyone explain, how to deal with this problem.

**Comment by Vinzent03** [comment] 2024-01-29 12:34
Do you have the same issue when starting the app in debug mode via `flutter run`, so without vscode?

**Comment by bangzaka** [comment] 2024-01-29 13:32
I have tried various ways, here are some of my notes:

1. When run start debug an exception will appear.
2. When running without debug the exception does not appear.
3. When the profile mode exception does not appear (cannot hot reload).
4. When the release mode does not appear.

I've added it
  <uses-permission android:name="android.permission.INTERNET"/>
in debug mode, profile and others.

I've tried flutter clean. but the exception still appears when running debug.

**Comment by dshukertjr** [comment] 2024-01-29 13:38
@bangzaka 
Would you be able to open a support ticket from [supabase.help](https://supabase.help) about this issue?

**Comment by Vinzent03** [comment] 2024-01-29 13:44
I guess it's because of the debug breakpoint setting in vscode. From what I understand the api url no longer resolves to ipv4 but ipv6 so it first tries ipv4, but fails causing an exception which I think gets caught.
What happens if you turn uncheck both boxes. Are your queries working then?

![image](https://github.com/supabase/supabase-flutter/assets/63981639/869060c1-39fa-4b2c-b34f-f8389078cd2e)

**Comment by dshukertjr** [comment] 2024-01-29 14:29
Hmm, you should be able to connect to your Supabase API via IPv4 though.

**Comment by dmeckers** [comment] 2024-02-06 19:36
I'm facing the same issue , tried on blank project both of my projects , even running with ipv6_lookup does not fixes this exception

**Comment by dshukertjr** [comment] 2024-02-07 01:01
@bangzaka 
Although the cause is unknown, it seems like you aren't having trouble running your app, so I'm going to close this issue. Feel free to re-open it if you run into the same issue in the future.

**Closed by dshukertjr** 2024-02-07 01:01 UTC
Labels: bug

**Comment by DKSingh1604** [comment] 2024-12-01 08:42
for me everything's working fine in run and debug mode but issue came when i generated an apk for my app, there on attempt to login or signup in my authentication app this error came up, someone knows any reason

**Comment by Vinzent03** [comment] 2024-12-01 16:15
@DKSingh1604 Did you follow the required steps [here](https://docs.flutter.dev/data-and-backend/networking) to allow internet connection for your app?
