### ISSUE TITLE
 The query does not return any data.

### ISSUE THREAD

**Issue by arnulfo4jc** [supabase/supabase-flutter#389] opened 2023-03-07 23:14 UTC
I can't get the data from the supabase database, I can't get the data from the tables.

In a first project with supabase everything worked fine, when I started a second project, I couldn't get data from the [tables.[]

  Future cargarTareas() async {
    final supabase = Supabase.instance.client;
    final data = await supabase.from('areas').select('nombre');
    print(data);
   
  }

returns an empty list.

**Comment by Vinzent03** [comment] 2023-03-07 23:35
I guess you have role level security enabled without or with wrong policies. https://supabase.com/docs/guides/auth/row-level-security

**Comment by dshukertjr** [comment] 2023-03-17 02:49
I would close this as it seems like the cause is what Vinzent has suggested, but feel free to reopen it if it isn't working after setting rls policies on the table!

**Closed by dshukertjr** 2023-03-17 02:49 UTC
Labels: bug
