### ISSUE TITLE
Realtime Stream Initalizing and Cancelling to Handle Errors

### ISSUE THREAD

**Issue by iampopal** [supabase/supabase-flutter#219] opened 2022-09-17 07:39 UTC
**Describe the bug**
Our app secondary feature is messaging, we listen to room_status using realtime stream. 

A stream can fail onError like having no internet connection.
when we initialize our stream again after error the stream is not listening to any changer

**To Reproduce**
1) Create a table and enable realtime
2) initialize the realtime
3) Close the internet then open the app
4) After the internet connection fails, the stream does not get realtime events (after initializing again)

or
1) Initialize a stream listener and cancel it and initialize it agian

**Expected behavior**
Realtime stream work with StreamSubscription so we can cancel and listen again to realtime streams.

**Additional context**
MacOS, Windows, Android and iOS

**Comment by iampopal** [comment] 2022-09-17 07:49
The issue main issue is 
we can listen to the stream only once when first time initializing 

if we close the screen and open it again, we cant listen to the stream again.

**Comment by dshukertjr** [comment] 2022-09-18 17:15
@iampopal 
Thanks for opening this issue. I am having trouble reproducing this issue. Here are the steps that I am doing:
1. Create a `StreamBuilder` like this:
  ```dart
  StreamBuilder(
    stream: Supabase.instance.client.from('posts').stream(['id']),
    builder: (context, snapshot) {
      if (snapshot.hasError) {
        print(snapshot.error.toString());
        return Text(snapshot.error.toString());
      }
      if (snapshot.connectionState != ConnectionState.active) {
        return const Center(child: CircularProgressIndicator());
      }
      return ListView.builder(
        itemCount: (snapshot.data as List).length,
        itemBuilder: ((context, index) {
          return ListTile(
            title: Text(
                (snapshot.data as List)[index]['content']?.toString() ??
                    ''),
          );
        }),
      );
    },
  ),
  ```
2. Open the app 
3. Update data from dashboard and observe that data is being updated on the Flutter app in realtime
4. Make the app go in background mode and open other app
5. Reopen the app again. 
6. Update data from dashboard and observe that the data is being updated on the Flutter app in realtime. 

It seems like with the above steps I didn't lose realtime connection. I tested it using Android phone and supabase-flutter v1.0.0-dev.7.

> After the internet connection fails, the stream does not get realtime events (after initializing again)

Also, could you explain what exactly you do when you say `initializing again` in the above sentence?

**Comment by iampopal** [comment] 2022-09-23 13:32
@dshukertjr  Thank you for your response

> @iampopal Thanks for opening this issue. I am having trouble reproducing this issue. Here are the steps that I am doing:
> 
> 1. Create a `StreamBuilder` like this:
> 
> ```dart
> StreamBuilder(
>   stream: Supabase.instance.client.from('posts').stream(['id']),
>   builder: (context, snapshot) {
>     if (snapshot.hasError) {
>       print(snapshot.error.toString());
>       return Text(snapshot.error.toString());
>     }
>     if (snapshot.connectionState != ConnectionState.active) {
>       return const Center(child: CircularProgressIndicator());
>     }
>     return ListView.builder(
>       itemCount: (snapshot.data as List).length,
>       itemBuilder: ((context, index) {
>         return ListTile(
>           title: Text(
>               (snapshot.data as List)[index]['content']?.toString() ??
>                   ''),
>         );
>       }),
>     );
>   },
> ),
> ```
> 
> 2. Open the app
> 3. Update data from dashboard and observe that data is being updated on the Flutter app in realtime
> 4. Make the app go in background mode and open other app
> 5. Reopen the app again.
> 6. Update data from dashboard and observe that the data is being updated on the Flutter app in realtime.
> 
> It seems like with the above steps I didn't lose realtime connection. I tested it using Android phone and supabase-flutter v1.0.0-dev.7.
> 
> > After the internet connection fails, the stream does not get realtime events (after initializing again)
> 
> Also, could you explain what exactly you do when you say `initializing again` in the above sentence?

Thank you for your response.

**Comment by dshukertjr** [comment] 2022-09-24 14:38
Thanks for the detailed description. I was able to reproduce the issue. 

Right now without re-initializing the stream, the stream will keep getting any updates after it comes back online, but the problem is that it loses any updates that happened during when the device was offline, it sounds like. 

@Vinzent03 I think the solution to this issue is to implement refetching upon coming back to online, but what do you think?
https://github.com/supabase-community/supabase-flutter/issues/90#issuecomment-1252179018

**Comment by dshukertjr** [comment] 2023-01-20 03:13
Just wanted to come back to this issue. Currently, Supabase's real-time feature requires an internet connection in order to provide real-time data. If the device goes offline, any data that was sent to the client from the server is lost. This is a known limitation of Supabase, and we do have some attempts to solve it like [this one](https://supabase.com/blog/postgres-crdt). Until we find a proper fix for it across all Supabase producets, Supabase will remain to have a stable internet connection as a requirement. With this, I will close this issue for now.

**Closed by dshukertjr** 2023-01-20 03:13 UTC
Labels: bug, realtime
