### ISSUE TITLE
Update supabase dependency to fix RealtimeSubscription Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by gcostaapps** [supabase/supabase-flutter#55] opened 2021-12-08 21:43 UTC
I'm running version 0.2.9 of supabase_flutter and started to get this error in my realtime, I think this is related to this [issue](https://github.com/supabase/supabase-dart/issues/64) that is already resolved. Can the supabase_flutter be upgraded to use 0.2.10 version of supabase? 

```
Error: Expected a value of type 'List<dynamic>', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:56672/dart_sdk.js:5061:11)
    at Object.castError (http://localhost:56672/dart_sdk.js:5020:15)
    at Object.cast [as as] (http://localhost:56672/dart_sdk.js:5345:17)
    at Function.as_C [as as] (http://localhost:56672/dart_sdk.js:4966:19)
    at WhereIterator.new.<anonymous> (http://localhost:56672/packages/supabase/src/supabase_realtime_payload.dart.lib.js:86:93)
    at WhereIterator.new.moveNext (http://localhost:56672/dart_sdk.js:23320:56)
    at MappedIterator.new.moveNext (http://localhost:56672/dart_sdk.js:23200:30)
    at JsIterator.next (http://localhost:56672/dart_sdk.js:6813:21)
    at Function.of (http://localhost:56672/dart_sdk.js:44586:18)
    at MappedIterable.__.toList (http://localhost:56672/dart_sdk.js:21359:30)
    at Function.fromJson (http://localhost:56672/packages/supabase/src/supabase_realtime_payload.dart.lib.js:86:280)
    at realtime_subscription.Binding.new.<anonymous> (http://localhost:56672/packages/supabase/src/supabase_realtime_client.dart.lib.js:48:83)
    at realtime_subscription.RealtimeSubscription.new.trigger (http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:494:12)
    at http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:918:145
    at WhereIterable.new.forEach (http://localhost:56672/dart_sdk.js:21308:11)
    at http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:918:117
    at realtime_client.RealtimeClient.new.<anonymous> (http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:1038:81)
    at realtime_client.RealtimeClient.new.onConnMessage (http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:923:12)
    at http://localhost:56672/packages/realtime_client/src/push.dart.lib.js:782:16
    at _RootZone.runUnaryGuarded (http://localhost:56672/dart_sdk.js:38448:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:56672/dart_sdk.js:32328:22)
    at _ControllerSubscription.new.[_add] (http://localhost:56672/dart_sdk.js:32277:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:56672/dart_sdk.js:35152:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:56672/dart_sdk.js:35256:32)
    at _SyncStreamController.new.[_add] (http://localhost:56672/dart_sdk.js:34966:26)
    at _SyncStreamController.new.add (http://localhost:56672/dart_sdk.js:34932:19)
    at _RootZone.runUnaryGuarded (http://localhost:56672/dart_sdk.js:38448:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:56672/dart_sdk.js:32328:22)
    at _ControllerSubscription.new.[_add] (http://localhost:56672/dart_sdk.js:32277:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:56672/dart_sdk.js:35152:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:56672/dart_sdk.js:35256:32)
    at _SyncStreamController.new.[_add] (http://localhost:56672/dart_sdk.js:34966:26)
    at _SyncStreamController.new.add (http://localhost:56672/dart_sdk.js:34932:19)
    at _StreamSinkWrapper.new.add (http://localhost:56672/dart_sdk.js:35290:24)
    at _GuaranteeSink.new.add (http://localhost:56672/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1120:24)
    at http://localhost:56672/packages/web_socket_channel/src/copy/web_socket_impl.dart.lib.js:1333:37
    at Object._checkAndCall (http://localhost:56672/dart_sdk.js:5268:16)
    at Object.dcall (http://localhost:56672/dart_sdk.js:5273:17)
    at WebSocket.<anonymous> (http://localhost:56672/dart_sdk.js:101824:100)
```

**Comment by bdlukaa** [comment] 2021-12-09 12:39
Duplicate of https://github.com/supabase-community/supabase-dart/issues/64

This is already fixed on supabase-dart.

**Comment by gcostaapps** [comment] 2021-12-09 12:46
Hi @bdlukaa, I see that it's fixed, but supabase_flutter doesn't use the updated version of supabase_dart. Maybe changing the title to something about this update?

**Comment by phamhieu** [comment] 2022-01-14 02:59
A new supabase-flutter version has been deployed. Can you try again and let us know if the problem persists.

**Closed** 2022-01-17 07:25 UTC
Labels: bug
