### ISSUE TITLE
Resource android:attr/lStar not found when building release APK

### ISSUE THREAD

**Issue by SUPERHUANG2** [supabase/supabase-flutter#1058] opened 2024-10-09 01:15 UTC
This error seems to be related to the sign_in_with_apple plugin.

Environment
supabase_flutter version: 1.10.25
sign_in_with_apple plugin version: 5.0.0
Android compileSdkVersion: 34
Android targetSdkVersion: 34
Steps to Reproduce
Add sign_in_with_apple plugin to pubspec.yaml
Run flutter pub get
Try to build a release APK with flutter build apk --release
What I've Tried
I've attempted the following solutions without success:

Updated Android SDK versions in build.gradle
Ensured AndroidX is enabled
Cleaned and rebuilt the project
Disabled resource shrinking and minification
Question
Is this a known issue with the plugin? Are there any workarounds or fixes available?

Any assistance would be greatly appreciated. Thank you!

**Comment by dshukertjr** [comment] 2024-10-09 15:38
Duplicate of https://github.com/supabase/supabase-flutter/issues/1057

**Closed by dshukertjr** 2024-10-09 15:38 UTC
Labels: bug
