### ISSUE TITLE
Invalid Refresh Token on restoreSession

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase-flutter#83] opened 2022-01-22 00:53 UTC
Hi. I have an issue where I have to login after the expiration time configured at Supabase UI passed.

**Steps to reproduce**
- Set expiration time to 2 min (Supabase UI, access token expiration?)
- Login & Persist Session e.g. local storage
- Quit app and wait 3 min
- Start app and call restoreSession

**Result**
"Invalid Refresh Token" gets returned from restoreSession

**Expected Behavior**
Fetches new access token and updates SupabaseClient state.

**Singleton Wrapper**
```dart
abstract class ISupabaseClientService {
  SupabaseClient get();
}

class SupabaseClientService implements ISupabaseClientService {
  final supabaseClient = SupabaseClient(
    EnvironmentService().supabaseUrl,
    EnvironmentService().supabaseKey,
  );

  @override
  SupabaseClient get() {
    return supabaseClient;
  }
}
```

**AuthService**

**SignIn**
```dart
@override
  Future<AppUser> signInWithEmail(String email, String password) async {
    var result = await _supabaseClientService.get().auth.signIn(email: email, password: password);

    await _saveSession();

    return AppUser( result.user?.id,  result.user.email,  result.user.email);
  }
```

**Called on app start**
```dart
@override
  Future<AppUser> getCurrentUser() async {
    var user = _supabaseClientService.get().auth.currentUser;

    if (user == null) {
      var session = await _getSession();
      var response = await _supabaseClientService.get().auth.recoverSession(session);

      if (response.error == null) await _saveSession();
      user = response.user;
    }

    return AppUser(
      user?.id,
      user?.email,
      user?.email,
    );
  }
```
**Private methods**
```dart
Future<void> _saveSession() async {
    final session = _supabaseClientService.get().auth.session();
    final SharedPreferences prefs = await _prefs;
    await prefs.setString('session', session.persistSessionString);
  }

  Future<String> _getSession() async {
    final SharedPreferences prefs = await _prefs;
    var session = (prefs.getString('session') ?? '');
    return session;
  }

  Future<void> _removeSession() async {
    final SharedPreferences prefs = await _prefs;
    await prefs.remove('session');
  }
```

**Persisted Session for restoreSession**
That's my token with the Invalid Refresh token error on my dev environment, not that critical to share.
`"{"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQyODA1ODIwLCJzdWIiOiIzMDc4ZjY2NS1jNjFiLTQ0Y2UtYjY3ZS1kNzIyOTNjMWFjMmMiLCJlbWFpbCI6InNlcmdlai5zYWNoc0BnbXguZGUiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.QQaZpPDTy1urjbZNoMf88I15HIIHIoGRPJN152ht06U","expires_in":120,"refresh_token":"ybqC0YdCNlYxByvlQh5WQA","token_type":"bearer","provider_token":null,"user":{"id":"3078f665-c61b-44ce-b67e-d72293c1ac2c","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"anymail@provider.com","created_at":"2022-01-20T12:12:57.382314Z","confirmed_at":"2022-01-20T12:12:57.387309Z","last_sign_in_at":"2022-01-21T22:55:00.788920397Z","role":"authenticated","updated_at":"2022-01-21T22:55:00.790273Z"}},"expiresAt":1642805820}"`

**RestoreSession works within that configured duration but else it returns that error.**

**Comment by bdlukaa** [comment] 2022-04-17 17:58
Seems related to https://github.com/supabase-community/supabase-flutter/issues/82

**Comment by dshukertjr** [comment] 2022-04-26 05:40
Hi @SergejSachs 

I wrote on [this](https://github.com/supabase/supabase/issues/5110) issue as well, but please let us know how the test went with any of the recent gotrue packages.

**Comment by dshukertjr** [comment] 2022-09-28 02:42
@Sesa1988 have you tried the supabase-flutter developer preview version?https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9

I wonder if you will still experience the same issue.

**Comment by Sesa1988** [comment] 2022-09-28 12:23
> @Sesa1988 have you tried the supabase-flutter developer preview version?https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9
> 
> I wonder if you will still experience the same issue.

I tried it on dev.7 and could not make it quickly work in general and thought I will wait until the full release.

It would be nice if the documentation for email/provider-authentication on multiple platforms and integration in general would be adjusted for the full release :)

Im waiting for the release for sure, especially for the desktop parts.

**Comment by dshukertjr** [comment] 2022-09-30 12:52
@Sesa1988 I am not able to reproduce issue. Token refresh after token expiring is working fine in multiple projects that I have. The cause could be either there is something wrong with your Supabase instance, or there is something wrong with the implementation. 

It seems like you are using the supabase-dart package, but have you tried supabase-flutter? It takes case of refreshing your token for you.

**Comment by serifmehmet** [comment] 2022-10-08 20:16
I tried on dev.9 and i got the same exception. I use shared_preferences to store persistentToken. 

pubspec:
supabase_flutter: ^1.0.0-dev.9

This is how i restore the session:

```
Future<Either<Failure, AuthUserModel>> restoreSession() async {
    final res = authTokenLocalDataSource.get();
    if (res.isLeft()) {
      return left(const Failure.empty());
    }

    final response = await authClient.recoverSession(res.getOrElse(() => ''));
    final data = response.user;

    if (response.statusCode != 200 || response.session == null) {
      await authTokenLocalDataSource.delete("auth-token");
      return left(const Failure.unauthorized());
    }

    await authTokenLocalDataSource.store(response.session?.persistSessionString ?? '');
    

    return right(AuthUserModel.fromJson(data!.toJson()));
}
```

This is the signIn method:

```
Future<Either<AuthFailure, AuthUserModel>> signIn(String phoneNumber, String password) async {
    final response = await authClient.signIn(phone: phoneNumber, password: password);
    if (response.user == null) {
      return left(const AuthFailure.wrongCredentials());
    }

    await authTokenLocalDataSource.store(response.session?.persistSessionString ?? '');
    await authTokenLocalDataSource.storeBool("logged-in", true);
    return Right(AuthUserModel.fromJson(response.user!.toJson()));
 }
```

**Comment by dshukertjr** [comment] 2022-10-09 05:48
@serifmehmet 
In your case, the issue is happening most likely because you have your own token refresh methods, and supabase-flutter is also storing and refreshing the token using hive in the background. You do not need to manage tokens by yourself even if you want to use SharedPreferences. Please refer to custom local storage section of the readme for more info on this!
https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9#custom-localstorage

**Comment by Sesa1988** [comment] 2022-10-14 21:24
> 

I started to integrate the new version into my app but noticed there is no "GetCurrentUser" interface anymore.
There is a "InitialSession" interface but this is not reliable for fetching the current user and login state? 

Basically any change even the checks for the current user after RunApp should be running over the stream subscription?

**Comment by Sesa1988** [comment] 2022-10-14 21:24
> @serifmehmet In your case, the issue is happening most likely because you have your own token refresh methods, and supabase-flutter is also storing and refreshing the token using hive in the background. You do not need to manage tokens by yourself even if you want to use SharedPreferences. Please refer to custom local storage section of the readme for more info on this! https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9#custom-localstorage

I started to integrate the new version into my app but noticed there is no "GetCurrentUser" interface anymore.
There is a "InitialSession" interface but this is not reliable for fetching the current user and login state? 

Basically any change even the checks for the current user after RunApp should be running over the stream subscription?

**Comment by dshukertjr** [comment] 2022-10-15 02:44
@Sesa1988 
You can get the user with `supabase.auth.currentUser`!

**Comment by Sesa1988** [comment] 2022-10-15 12:35
> @Sesa1988 You can get the user with `supabase.auth.currentUser`!

Thanks, but it seems like I cant await provider-logins and check myself the current status? This needs to be done via onAuthStateChange?

**Comment by dshukertjr** [comment] 2022-10-15 12:56
@Sesa1988 Yup, for provider login, you have to wait for singin event on onAuthStateChange. 

We will look into signout. Thanks for letting us know.

**Comment by Sesa1988** [comment] 2022-10-15 18:19
> @Sesa1988 Yup, for provider login, you have to wait for singin event on onAuthStateChange.
> 
> We will look into signout. Thanks for letting us know.

Is it possible to expose a stream only to social providers like redirects for provider sessions? This way everything else could be handled without onAuthStateChange. My issue is I have to change many things and test it again because if I use onAuthStateChange everything gets triggered twice and there is no option to see where the User Event is from, its just a signedIn event.

**Comment by dshukertjr** [comment] 2022-10-17 09:42
@Sesa1988 
>Is it possible to expose somehow the session from the provider redirects without onAuthStateChange? Like signInWithProvider could return the session or a special listener for provider session returns?

No, the way to detect signIn is to listen to onAuthStateChange only.

**Comment by Sesa1988** [comment] 2022-10-17 17:46
> @Sesa1988
> 
> > Is it possible to expose somehow the session from the provider redirects without onAuthStateChange? Like signInWithProvider could return the session or a special listener for provider session returns?
> 
> No, the way to detect signIn is to listen to onAuthStateChange only.

Okay got it, I will change my setup then. Looks like the signout issue was my mistake, my bad :)

**Comment by dshukertjr** [comment] 2022-10-18 01:56
@Sesa1988 Amazing!

**Comment by dshukertjr** [comment] 2023-02-14 03:44
I will close this issue as it seems like the issue was resolved, but feel free to reopen it if anything persists.

**Closed by dshukertjr** 2023-02-14 03:44 UTC
Labels: bug, auth
