### ISSUE TITLE
Error when trying to fetch data with a column of type int8

### ISSUE THREAD

**Issue by lucas3g** [supabase/supabase-flutter#348] opened 2023-02-06 12:14 UTC
**Describe the bug**
When I try to do a select with eq using a column of type int8 it returns an exception.
![image](https://user-images.githubusercontent.com/53888064/216967594-be1f1737-1032-4f79-82ee-9d85727b2116.png)

**To Reproduce**
1. To reproduce the error just have a table with an int8 column and try to fetch the data.
2. ![image](https://user-images.githubusercontent.com/53888064/216968053-bfb6b183-9d1a-4e70-82c1-1f1830cafd5b.png)
3. ![image](https://user-images.githubusercontent.com/53888064/216968080-3e499ce2-d623-4ace-9f99-bb74797bbe98.png)

**Expected behavior**
Return all data from the table according to the filter that was passed

**Screenshots**
![image](https://user-images.githubusercontent.com/53888064/216967594-be1f1737-1032-4f79-82ee-9d85727b2116.png)

**Version (please complete the following information):**
 - [e.g. 1.4.0]

**Additional context**
In version 0.3.3 this problem does not happen.

**Comment by Vinzent03** [comment] 2023-02-06 12:16
What's the type of `params.value`?

**Comment by lucas3g** [comment] 2023-02-06 12:16
int

**Comment by dshukertjr** [comment] 2023-02-06 12:32
@lucas3g Could you hard code all of your table names, column name, and values and see if that works? Chances are, one of the variables have unexpected type.

I just tried it like this and couldn't reproduce. 
```dart
  final data =
      await supabase.from('my_table').select().eq('int_column', 10);
  print(data);
```

**Comment by lucas3g** [comment] 2023-02-06 12:37
The strange thing is that in version 0.3.3 it works perfectly hahah

**Comment by lucas3g** [comment] 2023-02-06 12:50
@dshukertjr I didn't understand what to do. Can you give me an example please?

**Comment by dshukertjr** [comment] 2023-02-06 12:58
@lucas3g 
We cannot tell what values you have in your variables, so could you provide an hard-coded example without using any variables like this that throws the error?

```dart
final data =
      await supabase.from('my_table').select().eq('int_column', 10);
```

**Comment by dshukertjr** [comment] 2023-02-06 13:05
@lucas3g Thanks. Could you also provide the full table definition of the `students` table?

**Comment by lucas3g** [comment] 2023-02-06 13:07
Updated the comment above

**Comment by dshukertjr** [comment] 2023-02-06 13:17
@lucas3g Couldn't reproduce. I created the same table, copied and pasted your query and it just worked fine. 

Did you try the hardcoded version on your end to see if that works?

**Comment by lucas3g** [comment] 2023-02-06 13:25
I tried and the same error happens :(

The strange thing is that in version 0.3.3 it works and I haven't modified anything.

```dart 
final result = await supa
        .from('students')
        .select()
        .eq('class', 10)
        .execute();

**Comment by dshukertjr** [comment] 2023-02-06 13:29
@lucas3g Just to double check, v0.3.3 doesn't throw error, but returns errors, but do you actually have the data returned in the your `result` variable with v0.3.3 with no errors?

**Comment by lucas3g** [comment] 2023-02-06 13:31
It does not return any errors.
The data arrives correctly as I expected.

**Comment by dshukertjr** [comment] 2023-02-06 13:38
Or, if the app is still under development, you can share the supabase URL and anon key so that I can directly make queries to your table from my end and see if I can reproduce it.

**Comment by lucas3g** [comment] 2023-02-06 13:45
https://oeuqtuxabkzeowqwjwnl.supabase.co
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldXF0dXhhYmt6ZW93cXdqd25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzQ5NTA1MjEsImV4cCI6MTk5MDUyNjUyMX0.U1M9ohWN4G0Abhb14Ct-8qAsdaLSmrjK8dnAvTMqhdA

**Comment by dshukertjr** [comment] 2023-02-06 14:03
@lucas3g 
I was able to see the error on my end, and found out that it's the `order()` clause that is causing it. When the `ascending` is false, the query works fine. Still couldn't reproduce it with my own Supabase project though.

If you create another Supabase project, would it happen?

**Comment by lucas3g** [comment] 2023-02-06 14:29
I will test

**Comment by lucas3g** [comment] 2023-02-06 17:07
Actually creating a new project, everything worked ok in version 1.4.0, now the question is why the old project doesn't work hahah

One thing I did a lot was to rename the columns, change the types, maybe there's a bug that doesn't really change the type.

**Comment by Vinzent03** [comment] 2023-02-06 18:53
@lucas3g May you compare your postgrest versions? You can see them here `https://<id>.supabase.co/rest/v1/`

**Comment by dshukertjr** [comment] 2023-02-07 02:59
@lucas3g 
Great to hear that it's working fine on a fresh project. 

Editing the columns might have been the cause of it. It might be a postgrest version issue like @Vinzent03 says, but it might also be an issue on the backend infrastructure. If you could open a ticket from [here](https://app.supabase.com/support/new) letting us know the project with the issue and the fact that changing column names and column types has resulted in the issue you are facing, we can probably get it fixed for any future Supabase users. 

While we work on that, I hope it is okay for you to start using the fresh Supabase project that is working fine. I'd like to close this issue for now as the issue seems like is on the backend side of things.

**Closed by dshukertjr** 2023-02-07 02:59 UTC
Labels: bug
