### ISSUE TITLE
The links on iOS and MacOS do not work with the latest flutter version

### ISSUE THREAD

**Issue by BentEngbers** [supabase/supabase-flutter#749] opened 2023-12-06 15:13 UTC
**Describe the bug**
The links back to the app used for auth do not work.

**Flutter version**
Flutter 3.16.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9e1c857886 (6 days ago) • 2023-11-30 11:51:18 -0600
Engine • revision cf7a9d0800
Tools • Dart 3.2.2 • DevTools 2.28.3

**Version (please complete the following information):**
├── supabase 1.11.11
│   ├── functions_client 1.3.2
│   ├── gotrue 1.12.6
│   ├── postgrest 1.5.2
│   ├── realtime_client 1.4.0
│   ├── storage_client 1.5.4
├── supabase_flutter 1.10.25
│   ├── supabase...

**Additional context**
Additional information can be found at the following issue: https://github.com/llfbandit/app_links/issues/82

**Fix**
Update/add the app_links dependency to 3.5.0-dev2 in the pubspec.yaml
```yaml
dependencies:
  app_links: ^3.5.0-beta.2
```

**Comment by mariopepe** [comment] 2023-12-15 14:41
I can confirm that after auth the redirect does not work on supabase `2.0.1`, had to downgarde to `1.10.25` and everything is working fine.

Unfortunately cannot offer minimum reproducible code as the auth logic is in too deep in my codebase and right now we are in a run getting to production, next week I'll try!

Flutter version `3.16.4`

**Comment by dshukertjr** [comment] 2023-12-15 14:47
@mariopepe 
This issue is not related to supabase_flutter itself, but its dependency app_link, and since app_link now has published v3.5.0, which includes a fix for this issue, redirect should work just fine on supabase_flutter v2.0.1. When using it, make sure you are using app_link v3.5.0 or later by inspecting your pubspec.lock file. 

If you are still unable to have the auth redirect with app_link v3.5.0, then you are most likely facing a different issue from the one described here.

**Comment by dshukertjr** [comment] 2024-01-22 03:42
We have updated the app_link version, so this issue should no longer happen.

**Closed by dshukertjr** 2024-01-22 03:42 UTC
Labels: bug
