### ISSUE TITLE
How do we sign in with Apple on Flutter for Android?

### ISSUE THREAD

**Issue by ellmaki** [supabase/supabase-flutter#811] opened 2024-01-26 16:02 UTC
This flow would really benefit from documentation. Following the guide [here](https://pub.dev/packages/sign_in_with_apple) is very confusing with Supabase. Specifically documentation around how to handle callback URL's would be appreciated. 

It seems like we are supposed to implement this callback
```
intent://callback?${PARAMETERS FROM CALLBACK BODY}#Intent;package=YOUR.PACKAGE.IDENTIFIER;scheme=signinwithapple;end

```

instead of the supa recommended:
```
io.supabase.yourapp://login-callback/
```

any insight here?

**Comment by dshukertjr** [comment] 2024-01-27 00:53
Thanks for pointing this out. We certainly lack documentation for Apple sign-in on Android. 

We currently recommend using `signInWithOAuth()` method to perform Apple sign-in on Android. Will make sure this is clear on the docs as well as our readme.

**Comment by mikkomcmenamin** [comment] 2024-02-25 15:09
I'm currently struggling with this too. Even when using signInWithOAuth() I can't seem to get the redirect link to work.

**Comment by dshukertjr** [comment] 2024-02-27 06:45
@mikkomcmenamin 
Can you follow the instructions here and see if you can make it work? 
https://supabase.com/docs/guides/auth/social-login/auth-apple?platform=flutter#apple-sign-in-on-android-web-windows-and-linux

**Comment by dshukertjr** [comment] 2024-03-08 09:26
I'm going to close this one as we have documentation on how to implement Apple sign-in on Android. 

https://supabase.com/docs/guides/auth/social-login/auth-apple?platform=flutter#apple-sign-in-on-android-web-windows-and-linux

**Closed by dshukertjr** 2024-03-08 09:26 UTC
Labels: documentation, enhancement, auth

**Comment by formalpair** [comment] 2024-04-16 19:18
Hey Tyler, Supabase team

Unfortunately I'm also struggling to handle properly the login on android with apple credentials.

I have followed all the documentation provided above.

The login on IOS works properly and smooth. 
The authentication on Android open the browser, make the auth and redirect successfully.
But, at the time which my app comes after the redirection with the magic link, the below issue occurs:

`AuthException(message: Unable to exchange external code%3A c669fc42a9ff149c7b778865ef977822f.0.mrtst.EItP3ITgGn7irEwox2E0Pw, statusCode: null)
I/flutter (27400): #0      GoTrueClient.getSessionFromUrl (package:gotrue/src/gotrue_client.dart:776:7)
I/flutter (27400): #1      SupabaseAuth._handleDeeplink (package:supabase_flutter/src/supabase_auth.dart:216:43)
I/flutter (27400): #2      SupabaseAuth._handleIncomingLinks.<anonymous closure> (package:supabase_flutter/src/supabase_auth.dart:170:13)
I/flutter (27400): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
I/flutter (27400): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter (27400): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter (27400): #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
I/flutter (27400): #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
I/flutter (27400): #8      AppLinksMethodChannel.uriLinkStream.<anonymous closure> (package:app_links/src/app_links_method_channel.dart:56:16)
I/flutter (27400): #9      _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
I/flutter (27400): #10     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
I/flutter (27400): #11     _RootZone.runUnaryGuarde`

I have upgraded my Postgres yesterday trying to fix it along with Flutter upgrade and supabase libs with no success.

**Comment by dshukertjr** [comment] 2024-04-17 01:30
@formalpair The `code` query parameter you received does not look like one created by the supabase_flutter library.

Did you happen to follow the instructions on the [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple) package for Android? If that is the case, then you need to remove any bit of code related to it as they are probably the cause of the sign-in not working. On [our docs](https://supabase.com/docs/guides/auth/social-login/auth-apple?platform=flutter#apple-sign-in-on-android-web-windows-and-linux) we write not to follow any of the instructions on the `sign_in_with_apple` package.

**Comment by formalpair** [comment] 2024-04-17 03:46
@dshukertjr Hey Tyler. My bad. As an attempt I tried to reuse an intent from flutter_facebook_auth which OAuth was properly working, and not realized that was similar procedure that the [docs](https://supabase.com/docs/guides/auth/social-login/auth-apple?platform=flutter#apple-sign-in-on-android-web-windows-and-linux) asked to avoid regarding [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple).

My attempt was made in order to get the properly redirection. Removing the intent and all code related to flutter_facebook_auth (I didn't followed the code for Android inside sign_in_with_apple), the Apple page load properly and after insert my credentials, validate the informations and confirm that I want to "continue using Apple sign with my email" the page seems load something on the top bar, but stop, and don't redirect back to my app. 

I have made all from the scratch with no success.

It indicates my configs is wrong inside my project? 

Im just using the below code as doc asked:

```
await supabase
            .auth.signInWithOAuth(OAuthProvider.apple,
          redirectTo: 'mydomain://login-callback/'
        );
```

mydomain://login-callback/ as registered as magic link inside the project.

Thank you.

**Comment by dshukertjr** [comment] 2024-04-17 03:51
@formalpair 
What happens when you call the following currently?
```dart
await supabase.auth.signInWithOAuth(OAuthProvider.apple,
  redirectTo: 'mydomain://login-callback/'
);
```

**Comment by formalpair** [comment] 2024-04-17 13:22
@dshukertjr 
At the moment that the code is called, the browser is opened, returns true and loads successfully the apple login page.

**Comment by formalpair** [comment] 2024-04-18 09:57
@dshukertjr Hey Tyler, Any clue from the issue? After put my cloud credentials on last screen above, apple validate them properly but the redirection back to my app didn't occurs

**Comment by formalpair** [comment] 2024-04-18 19:40
Hey Guys. Sorry to bother you with it.

I have created a project from scratch using only supabase libs and the issue occurs again:

```
I/flutter ( 8650): AuthException(message: Unable to exchange external code%3A c009914a570e842199bfc4fb8f914b577.0.mrtst.o24Kx5pdERNdm4R8sQv0rw, statusCode: null)
I/flutter ( 8650): #0      GoTrueClient.getSessionFromUrl (package:gotrue/src/gotrue_client.dart:776:7)
I/flutter ( 8650): #1      SupabaseAuth._handleDeeplink (package:supabase_flutter/src/supabase_auth.dart:218:43)
I/flutter ( 8650): #2      SupabaseAuth._handleIncomingLinks.<anonymous closure> (package:supabase_flutter/src/supabase_auth.dart:170:13)
I/flutter ( 8650): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
I/flutter ( 8650): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter ( 8650): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 8650): #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
I/flutter ( 8650): #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
I/flutter ( 8650): #8      AppLinksMethodChannel.uriLinkStream.<anonymous closure> (package:app_links/src/app_links_method_channel.dart:56:16)
I/flutter ( 8650): #9      _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
I/flutter ( 8650): #10     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
I/flutter ( 8650): #11     _RootZone.runUnaryGuarde
```

I'll open a new issue.

**Comment by formalpair** [comment] 2024-04-19 13:26
Hello @dshukertjr
I have followed again the docs and after few new attempts, it worked properly. Sorry for the confusion and bother you.

Please keep posting videos from Flutter. We really love them.
Thanks again for all effort from you and Supabase team. You guys are amazing.
It has been a year which Im developing by myself a product, and you and Supabase are part of my learnings, codes and making this to come true. Thank you so much.

To help others like me:

Inside Supabase create the Redirect URL with no "https" and ensure that your domain follow your app domain.
Ex: your app is 'com.myapp.app'. Create your URL using 'com.myapp://login-callback/' for example.
Don't know the reason, but it worked only following this.
