### ISSUE TITLE
popup option for logging in, in place of the fullscreen webview

### ISSUE THREAD

**Issue by bertuz** [supabase/supabase-flutter#429] opened 2023-04-02 15:24 UTC
**Is your feature request related to a problem? Please describe.**
The auth process opens a fullscreem webview: it'd be nice having the chance of a modal way to open it, in place of a fullscreen one. this way the user is more aware of the context. 

**Describe the solution you'd like**
an option to choose between the fullscreen webview and a modal one, like the one below:
<img width="419" alt="uSquw" src="https://user-images.githubusercontent.com/3980392/229362504-de7769c0-295b-4aa6-804e-174a0e5d572a.png">

**Comment by dshukertjr** [comment] 2023-04-02 23:53
We are working on this feature right now!

Duplicate of https://github.com/supabase/supabase-flutter/issues/5

**Closed by dshukertjr** 2023-04-02 23:53 UTC
Labels: enhancement
