### ISSUE TITLE
Updating specific column in a row does not return the rest of the row in realtime stream

### ISSUE THREAD

**Issue by alexrabin** [supabase/supabase-flutter#272] opened 2022-11-09 03:28 UTC
**Describe the bug**
When updating one column in a row, not all the data in the row is sent back in the realtime stream.

**To Reproduce**
1. Create user table and enable realtime functionality in gui
```
CREATE TABLE IF NOT EXISTS public.users (
inserted_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
updated_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
user_id uuid NOT NULL,
alarms json NULL,
"wakeUpSchedules" json NULL,
quotes json NULL,
PRIMARY KEY (user_id)
);
```
2. Alter user table for update and delete to show in realtime streams `alter table users replica identity full;`
3. Create a record in the database however you choose.
4. Listen to realtime as a stream:
```
var user = client.auth.currentUser;

client
      .from('users')
      .stream(primaryKey: ['user_id'])
      .eq('user_id', user.id)
      .limit(1)
      .listen((event) {
       print(event);
});
```
5. Update quotes column to be an array of strings
<details>
<summary>Example Quotes List</summary>
<br/>
[
  "Great leaders inspire greatness in others.",
  "Belief is not a matter of choice, but conviction.",
  "Easy is the path to wisdom for those who are not blinded by themselves.",
  "You hold onto friends by keeping your heart a little softer than your head.",
  "Heroes are made by the times.",
  "Ignore your instincts at your peril.",
  "Most powerful is he who controls his own power.",
  "The winding path to peace is always a worthy one, regardless of how many turns it takes.",
  "Fail with honor rather than succeed with fraud.",
  "Greed and fear of loss are the roots that lead to the tree of evil.",
  "When surrounded by war, one must eventually choose a side.",
  "Arrogance diminishes wisdom.",
  "Truth enlightens the mind, but won’t always bring happiness to your heart.",
  "Fear is a disease; hope is the only cure.",
  "A single chance is a galaxy of hope.",
  "It is a rough road that leads to the heights of greatness.",
  "The costs of war can never be truly accounted for.",
  "Compromise is a virtue to be cultivated, not a weakness to be despised.",
  "A secret shared is a trust formed.",
  "A lesson learned is a lesson earned.",
  "Overconfidence is the most dangerous form of carelessness.",
  "The first step to correcting a mistake is patience.",
  "A true heart should never be doubted.",
  "Believe in yourself or no one else will.",
  "No gift is more precious than trust.",
  "Sometimes, accepting help is harder than offering it.",
  "Attachment is not compassion.",
  "For everything you gain, you lose something else.",
  "It is the quest for honor that makes one honorable.",
  "Easy isn’t always simple.",
  "If you ignore the past, you jeopardize the future.",
  "Fear not for the future, weep not for the past.",
  "In war, truth is the first casualty.",
  "Searching for the truth is easy. Accepting the truth is hard.",
  "A wise leader knows when to follow.",
  "Courage makes heroes, but trust builds friendship.",
  "Choose what is right, not what is easy.",
  "The most dangerous beast is the beast within.",
  "Who my father was matters less than my memory of him.",
  "Adversity is a friendship’s truest test.",
  "Revenge is a confession of pain.",
  "Brothers in arms are brothers for life.",
  "Fighting a war tests a soldier’s skills, defending his home tests a soldier’s heart.",
  "When there’s a will, there’s a way.",
  "A child stolen is a hope lost.",
  "The challenge of hope is to overcome corruption.",
  "Those who enforce the law must obey the law.",
  "The future has many paths - choose wisely.",
  "A failure for planning is a plan for failure.",
  "Love comes in all shapes and sizes.",
  "Fear is a great motivator.",
  "Truth can strike down the spectre of fear.",
  "The swiftest path to destruction is through vengeance.",
  "Evil is not born, it is taught.",
  "The path to evil may bring great power, but not loyalty.",
  "Balance is found in the one who faces his guilt.",
  "He who surrenders hope, surrenders life.",
  "He who seeks to control fate shall never find peace.",
  "Adaptation is the key to survival.",
  "Anything that can go wrong will.",
  "Without honor, victory is hollow.",
  "Without humility, courage is a dangerous game.",
  "A great student is what the teacher hopes to be.",
  "When destiny calls, the chosen have no choice.",
  "Only through fire is a strong sword forged.",
  "Crowns are inherited, kingdoms are earned.",
  "Who a person truly is cannot be seen with the eye.",
  "Understanding is honoring the truth beneath the surface.",
  "Who’s the more foolish, the fool or the fool who follows him?",
  "The first step towards loyalty is trust.",
  "The path of ignorance is guided by fear.",
  "The wise man leads, the strong man follows.",
  "Our actions define our legacy.",
  "Where we are going always reflects where we came from.",
  "Those who enslave others, inevitably become slaves themselves.",
  "Great hope can come from small sacrifices.",
  "Friendship shows us who we really are.",
  "All warfare is based on deception.",
  "Keep your friends close, but keep your enemies closer.",
  "The strong survive, the noble overcome.",
  "Trust is the greatest of gifts, but it must be earned.",
  "One must let go of the past to hold on to the future.",
  "Who we are never changes, who we think we are does.",
  "A fallen enemy may rise again, but the reconciled one is truly vanquished.",
  "The enemy of my enemy is my friend.",
  "Strength of character can defeat strength in numbers.",
  "Fear is a malleable weapon.",
  "To seek something is to believe in its possibility.",
  "Struggles often begin and end with the truth.",
  "Disobedience is a demand for charge.",
  "He who faces himself, finds himself.",
  "The young are often underestimated.",
  "When we rescue others, we rescue ourselves.",
  "Choose your enemies wisely, as they may be your last hope.",
  "Humility is the only defense against humiliation.",
  "When all seems hopeless, a true hero gives hope.",
  "A soldier’s most powerful weapon is courage.",
  "You must trust in others or success is impossible.",
  "One vision can have many interpretations.",
  "Alliances can stall true intentions.",
  "Morality separates heroes from villains.",
  "Sometimes even the smallest doubt can shake the greatest belief.",
  "Courage begins by trusting oneself.",
  "Never become desperate enough to trust the untrustworthy.",
  "Never give up hope, no matter how dark things seem.",
  "The truth about yourself is always the hardest to accept.",
  "The wise benefit from a second opinion.",
  "When in doubt, go to the source.",
  "The popular belief isn’t always the correct one.",
  "To love, is to trust, To trust is to believe.",
  "Jealousy is the path to chaos.",
  "Deceit is the weapon of greed.",
  "Without darkness there cannot be light.",
  "Wisdom is born in fools as well as wise men.",
  "What is lost is often found.",
  "Madness can sometimes be the path to truth.",
  "Death is just the beginning.",
  "Facing all that you fear will free you from yourself.",
  "Embrace others for their differences, for that makes you whole.",
  "The search for truth begins with belief.",
  "Survival is one step on the path to living.",
  "Trust placed in another is trust earned.",
  "If there is no path before you, create your own.",
  "Mistakes are valuable lessons often learned too late.",
  "Who you were does not have to define who you are.",
  "You can change who you are, but you cannot run from yourself.",
  "A plan is only as good as those who see through it.",
  "Don’t pay attention to the whole staircase, just the step in front of you"
]
</details>
6. Stream is correct:

```
[{alarms: [{enabled: true, id: 5307, ringTone: Aura, time: 2022-11-08T21:07:00.000}], inserted_at: 2022-11-09T03:06:50.585963+00:00, name: null, quotes: [Great leaders inspire greatness in others., Belief is not a matter of choice, but conviction., Easy is the path to wisdom for those who are not blinded by themselves., You hold onto friends by keeping your heart a little softer than your head., Heroes are made by the times., Ignore your instincts at your peril., Most powerful is he who controls his own power., The winding path to peace is always a worthy one, regardless of how many turns it takes., Fail with honor rather than succeed with fraud., Greed and fear of loss are the roots that lead to the tree of evil., When surrounded by war, one must eventually choose a side., Arrogance diminishes wisdom., Truth enlightens the mind, but won’t always bring happiness to your heart., Fear is a disease; hope is the only cure., A single chance is a galaxy of hope., It is a rough road that le<…>
```
7. Update alarms table through code or through the supabase dashboard
8. Response doesn't include quotes array:

```
[{alarms: [{enabled: true, id: 5307, ringTone: Aura, time: 2022-11-08T21:07:00.000}], inserted_at: 2022-11-09T03:06:50.585963+00:00, name: null, updated_at: 2022-11-08T20:20:14.877382+00:00, user_id: 102b20a7-8f2a-4123-8457-6d8ce03f44fa, wakeUpSchedules: null}]
```
10. Go back to dashboard, refresh and the quotes data is still there (it wasn't deleted)
11. Add a quote to the list for example and the realtime database stream will return correctly:
```
[{alarms: [{enabled: true, id: 5307, ringTone: Aura, time: 2022-11-08T21:07:00.000}], inserted_at: 2022-11-09T03:06:50.585963+00:00, name: null, quotes: [Great leaders inspire greatness in others., Belief is not a matter of choice, but conviction., Easy is the path to wisdom for those who are not blinded by themselves., You hold onto friends by keeping your heart a little softer than your head., Heroes are made by the times., Ignore your instincts at your peril., Most powerful is he who controls his own power., The winding path to peace is always a worthy one, regardless of how many turns it takes., Fail with honor rather than succeed with fraud., Greed and fear of loss are the roots that lead to the tree of evil., When surrounded by war, one must eventually choose a side., Arrogance diminishes wisdom., Truth enlightens the mind, but won’t always bring happiness to your heart., Fear is a disease; hope is the only cure., A single chance is a galaxy of hope., It is a rough road that le<…>
```

**Expected behavior**
The entire row should return correctly in the realtime database stream when a specific column is updated in that row.

**Smartphone (please complete the following information):**
 Supabase Client Version 1.1.0
Occurs on these tested devices:
- iPhone 14 Pro Simulator iOS 16.1
- iPhone 12 Physical Device iOS 16.1
- MacOS Ventura 13.0

<details>
<summary>Flutter Doctor</summary>
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.7 on channel stable at /Users/[user]/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (7 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/[user]/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
...

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Additional context**
I used the realtime inspector and the realtime data is not displayed  correctly. The old data has the correct data but the new data doesn't either.

Here is a [template](https://realtime.supabase.co/inspector/new?channel=supabase&log_level=debug&path=&project=&schema=public&table=users) make sure to use the server role key to ensure any rls policies work correctly

From what I see Supabase has a [1 mb limit](https://supabase.com/docs/guides/realtime/rate-limits#payload-limits) for realtime but this payload is less than 10kb.

**Comment by dshukertjr** [comment] 2022-11-09 04:13
@alexrabin 
With the sample data you provided, I was able to reproduce this issue. I was doing some testing, and it seems like this is something that only occurs when the `quotes` is large. When I tested with `["aaa", "bbb"]` as the value for quotes, I could not reproduce this issue. 

Looking into what is causing this right now!

**Comment by dshukertjr** [comment] 2022-11-09 04:56
@alexrabin 
Okay, this is a very weird issue. Thank you so much for finding this one. I actually was able to reproduce this issue with the Javascript SDK as well. I have shared my findings as well as the steps to reproduce that you have provided with the realtime team. When I look at the actual data that we receive on websocket, it seems like 'quotes' column is just not coming through sometimes, which seems like an issue on the backend. 

Here is a screenshot of the network tab with an app that I made using the javascript SDK. 
<img width="1121" alt="Screen Shot 2022-11-09 at 13 37 59" src="https://user-images.githubusercontent.com/18113850/200741758-e7b98774-d44c-483e-a1e7-328d9ab6b650.png">

I will keep this issue opened just in case for now.

**Comment by alexrabin** [comment] 2022-11-09 04:59
@dshukertjr does the real-time inspector not use the JavaScript sdk? The real-time inspector showed the correct data.

**Comment by dshukertjr** [comment] 2022-11-09 05:48
@alexrabin 

Yup, I think the realtime inspector uses the JavaScript SDK as well. 

If you look at the payload in the inspector carefully, it looks something like this, where it contains both the old and new record. Any chance what you thought was the "correct data" was the old data, and not the new one?

```javascript
{
    "schema": "public",
    "table": "user_data",
    "commit_timestamp": "2022-11-09T05:42:22Z",
    "eventType": "UPDATE",
    "new": {
        "alarms": [
            {
                "enabled": true,
                "id": "aaa",
                "ringtone": "aurora",
                "time": "2022-11-17 01:57:36+00"
            },
            {
                "enabled": false,
                "id": "aaa",
                "ringtone": "aurora",
                "time": "2022-11-17 01:57:36+00"
            }
        ],
        "inserted_at": "2022-11-11T01:57:31+00:00",
        "updated_at": "2022-11-17T01:57:36+00:00",
        "user_id": "84bb615c-3489-45a4-88fc-722a52fee5a9",
        "wakeUpSchedules": {
            "enabled": false,
            "id": "aaa",
            "ringtone": "aurora",
            "time": "2022-11-17 01:57:36+00"
        }
    },
    "old": {
        "alarms": [
            {
                "enabled": false,
                "id": "aaa",
                "ringtone": "aurora",
                "time": "2022-11-17 01:57:36+00"
            },
            {
                "enabled": false,
                "id": "aaa",
                "ringtone": "aurora",
                "time": "2022-11-17 01:57:36+00"
            }
        ],
        "inserted_at": "2022-11-11T01:57:31+00:00",
        "quotes": [
            "Great leaders inspire greatness in others.",
            "Belief is not a matter of choice, but conviction.",
            ...
            "A plan is only as good as those who see through it.",
            "Don’t pay attention to the whole staircase, just the step in front of you"
        ],
        "updated_at": "2022-11-17T01:57:36+00:00",
        "user_id": "84bb615c-3489-45a4-88fc-722a52fee5a9",
        "wakeUpSchedules": {
            "enabled": false,
            "id": "aaa",
            "ringtone": "aurora",
            "time": "2022-11-17 01:57:36+00"
        }
    },
    "errors": null
}
```

**Comment by alexrabin** [comment] 2022-11-09 11:37
I'm using the flutter stream builder not the channel on subscribe so I don't have control to check old vs new.

**Comment by alexrabin** [comment] 2022-11-09 12:36
@dshukertjr yeah you're correct that's what I am seeing in the inspector

**Comment by w3b6x9** [comment] 2022-11-09 21:58
@alexrabin @dshukertjr thanks for creating and confirming this issue. we'll investigate this shortly.

**Comment by w3b6x9** [comment] 2022-11-10 18:57
@olirice thanks for the context!

> when max_record_bytes is exceeded, we filter out columns

I thought that when the `max_record_bytes` limit was exceeded both `record` and `old_record` would be set to empty objects and error is returned: https://github.com/supabase/walrus#error-413-payload-too-large.

From my own testing and @alexrabin and @dshukertjr's testing it appears that `quotes` data returns in the `old` but not the `new`.

**Comment by olirice** [comment] 2022-11-10 20:10
> I thought that when the max_record_bytes limit was exceeded both record and old_record would be set to empty objects

That was the original behavior but it was updated in response to this issue https://github.com/supabase/realtime/issues/252
the doc you referenced is out of date, I'll open a PR to update it

> and error is returned

yes, sorry I forgot to mention that. You can where the error message is added [here](https://github.com/supabase/walrus/blob/49cc1ccb096eb3ae7841ffaa62e1c69c543daa28/sql/walrus_migration_0003_delete_filters_bugfix.sql#L270-L278)

**Comment by w3b6x9** [comment] 2022-11-10 20:13
> That was the original behavior but it was updated in response to this issue https://github.com/supabase/realtime/issues/252

@olirice Ah, that's right!

@alexrabin I think the workaround is to take the primary key(s) and query your table for the data that you're missing out on.

**Comment by alexrabin** [comment] 2022-11-10 20:50
@w3b6x9 I don't think I understand. What do you mean?

**Comment by w3b6x9** [comment] 2022-11-11 02:09
@alexrabin I mean that once an update comes through via Realtime, you can take the primary key that's part of the `new` data, and make a postgrest query to fetch the `quotes` data.

**Comment by alexrabin** [comment] 2022-11-11 23:56
> @alexrabin I mean that once an update comes through via Realtime, you can take the primary key that's part of the `new` data, and make a postgrest query to fetch the `quotes` data.

This in theory works but I would prefer if Supabase handled this better internally on the infrastructure side so I don't have to use this hack on web and flutter.

**Comment by w3b6x9** [comment] 2022-11-12 00:04
@alexrabin Everyone on hosted Realtime has the same default payload size limit but in the near future we'll enable custom limit size so you won't have to do this workaround.

**Comment by dshukertjr** [comment] 2022-11-12 02:39
@w3b6x9 

Just for personal reference, how do we receive [this error](https://github.com/supabase/walrus/blob/49cc1ccb096eb3ae7841ffaa62e1c69c543daa28/sql/walrus_migration_0003_delete_filters_bugfix.sql#L270-L278) from the realtime client library? Does it come through as an error in `.subscribe()`?

**Comment by w3b6x9** [comment] 2022-11-12 18:28
> Just for personal reference, how do we receive [this error](https://github.com/supabase/walrus/blob/49cc1ccb096eb3ae7841ffaa62e1c69c543daa28/sql/walrus_migration_0003_delete_filters_bugfix.sql#L270-L278) from the realtime client library? Does it come through as an error in `.subscribe()`?

@dshukertjr errors, like the one you linked to, will come through the change payload itself. see: https://github.com/supabase/realtime-js/blob/59bd47956ebe4e23b3e1a6c07f5fe2cfe943e8ad/src/RealtimeChannel.ts#L31

**Comment by alexrabin** [comment] 2023-02-12 22:04
@dshukertjr why was this closed? I am still encountering the issue where one column isn't being returned in the realtime stream

**Comment by dshukertjr** [comment] 2023-02-15 03:47
@alexrabin 
My apologies. I thought we had nailed down the cause [here](https://github.com/supabase/supabase-flutter/issues/272#issuecomment-1310669052). However, it seems like in this case both of the cause might not be the one that is causing the issue. 

For 1. `replica identity full` is set, and yet the payload is not coming through.
For 2. max message size is 250 kb for free project according to our [pricing page](https://supabase.com/pricing), and our testing payload is about 24 kb

@olirice It seems like neither one of [these](https://github.com/supabase/supabase-flutter/issues/272#issuecomment-1310669052) were the cause of this issue, but would you happen to have any other thoughts on what might be the cause? 

Here is a short video explaining what is happening here:
https://www.loom.com/share/28518b27497849d3bca43dc5068038de

The replica identity is set to full for the table that I'm testing.

**Comment by olirice** [comment] 2023-02-15 20:13
@dshukertjr thanks for the video ref, that was very helpful

I created a new test case in `supabase/walrus` and am not able to reproduce that result. Hear a link to the [PR](https://github.com/supabase/walrus/pull/67). In `test/expected/test_unchanged_toast.out` you can see `body1`, `body2`, and `body3` all in `record` and `old_record`.

Could you please upload a `.sql` dump of the schema from your example with the same data so I can make sure we're comparing 1:1?

**Comment by dshukertjr** [comment] 2023-02-27 06:02
@olirice Sorry for coming back late on this one. Here is the table and data that I was testing out.

```sql
-- Table 
create table "public"."user_data" (
    "inserted_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "user_id" uuid not null,
    "alarms" json,
    "wakeUpSchedules" json,
    "quotes" json
);

-- seed data
insert into public.user_data ("user_id", "inserted_at", "updated_at", "alarms", "wakeUpSchedules", "quotes")
values ('ac25ef0a-e64d-488d-884b-1d2c52242882', '2022-11-11 01:57:31+00', '2022-11-17 01:57:36+00', '[{"enabled":true,"id":"aaa","ringtone":"aurora","time":"2022-11-17 01:57:36+00"},{"enabled":false,"id":"aaa","ringtone":"aurora","time":"2022-11-17 01:57:36+00"}]', '{"enabled":false,"id":"aaa","ringtone":"aurora","time":"2022-11-17 01:57:36+00"}', '{"enabled":false,"id":"aaa","ringtone":"aurora","time":"2022-11-17 01:57:36+00"}');
```

**Comment by olirice** [comment] 2023-03-07 19:27
my turn to apologize for a late reply! (was ooo last week)

I tried it out with the table/data setup ^ and was still not able to reproduce but I did find

https://github.com/MaterializeInc/materialize/blob/d238cb464be5f8fc68c34cb5d1b013e3fc476870/src/storage/src/source/postgres.rs#L1057-L1065

which shows them handling unchanged toast values in the "new" record by copying them over from the "old" record. I'll continue trying to get a reproducible case, but either way will get a PR prepared with that new logic and then coordinate with you to test it out so we can be sure it resolves the problem

**Comment by olirice** [comment] 2023-03-07 20:46
scratch that! was able to get a reproducible case by turning off compression on the columns with
```sql
alter table public.notes alter column body2 set storage external;
```

this issue will be resolved by https://github.com/supabase/walrus/pull/67. I tagged you for review.

Note (optional):
you can double check that it resolves your exampleby running [this migration](https://github.com/supabase/walrus/blob/5930c62a52d1bdcef54dfd2ba9a5bd9d35d70743/sql/walrus_migration_0009_unchanged_toast.sql) into the database and then re-running the process from the loom video

**Comment by dshukertjr** [comment] 2023-03-18 03:38
@olirice 
I can confirm this is now working on our cloud instances!

**Closed by dshukertjr** 2023-03-18 03:38 UTC
Labels: bug, realtime
