### ISSUE TITLE
FormatException: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by thecavus** [supabase/supabase-flutter#293] opened 2022-11-28 16:47 UTC
When I update data in the table like below, I get an error as I shared in the screenshot.
``` dart
   static arkadasAramaIstegiGonder(
      String arananUid, CagriIstegi cagriIstegi) async {
    try {
      await client
          .from("kayitlar")
          .update({
            "gelen_arama": {
              "cagriKodu": cagriIstegi.cagriKodu,
              "arayanUid": cagriIstegi.arayanUid,
              "arananUid": cagriIstegi.arananUid
            }
          })
          .eq("uid", arananUid)
          .execute();
    } catch (e) {
      print(e);
      
    }
  }
```

![image](https://user-images.githubusercontent.com/90723530/204331543-36906dbc-fa84-46f4-a501-613898fe3d30.png)

**Comment by dshukertjr** [comment] 2022-11-29 01:08
@thecavus 
Thanks for opening this issue!

Could you the type definition of `CagriIstegi` used here?

**Comment by thecavus** [comment] 2022-11-30 22:04
this is my `CagriIstegi`  class.

``` dart
class CagriyaCevap {
  CagriyaCevap({
    required this.cagriKodu,
    required this.cevaplayanUid,
    required this.verilenCevap,
  });

  String cagriKodu;
  String cevaplayanUid;
  String verilenCevap;

  factory CagriyaCevap.fromJson(Map<String, dynamic> json) => CagriyaCevap(
        cagriKodu: json["cagriKodu"],
        cevaplayanUid: json["cevaplayanUid"],
        verilenCevap: json["verilenCevap"],
      );

  Map<String, dynamic> toJson() => {
        "cagriKodu": cagriKodu,
        "cevaplayanUid": cevaplayanUid,
        "verilenCevap": verilenCevap,
      };
}
```

and this is how i use it

``` dart

  arkadasAra(String uidArkadas) async {
    // 0 arama kodu(kod üretilir gelen cevap ile aynı mı diye bakılır ki bir yanlışlık olmasın)
    // 1 arayan kişinin uid si
    // 2 aranan kişinin uid si

    CagriIstegi cagriIstegi = CagriIstegi(
        cagriKodu: DatabaseService.cagriKoduOlustur(),
        arayanUid: DatabaseService.myUid,
        arananUid: uidArkadas);
    gonderilenCagriKodu = cagriIstegi.cagriKodu;

    LocalDatabaseKayitlar.setCagriIstegi(cagriIstegi);
    var arkadasDurumBilgisi = await DatabaseService.getDurumBilgisi(
        uidArkadas); // aranacak arkadaşın müsaitlik bilgisi alınır ve kontrol edilir

    // Aradığım kişi musait ise arama isteği gönder
    if (arkadasDurumBilgisi == "musait") {
      // Artık database_dinleyici_service içindeki metot ile gelecek cevap belenir ve olumlu ise arananlar_arkadas tablosuna kayıt yapılır.

      await DatabaseService.arkadasAramaIstegiGonder(uidArkadas, cagriIstegi);
      print("Aranan arkadas uid : " + uidArkadas);
    } else {
      print("aranan arkadas $uidArkadas  musait degil");
    }
    //TODO :aranan kişi müsait değilse yapılacakları unutma

    // TODO : artik gelecek cevabi dinlemeye başlayabilirsin
  }
```

**Comment by dshukertjr** [comment] 2022-12-01 05:16
@thecavus 
Would you be able to provide the raw value of this map that is causing the issue? like what is inside `cagriIstegi.cagriKodu`, `cagriIstegi.arayanUid`, and `cagriIstegi.arananUid`?

```dart
{
  "gelen_arama": {
    "cagriKodu": cagriIstegi.cagriKodu,
    "arayanUid": cagriIstegi.arayanUid,
    "arananUid": cagriIstegi.arananUid
  }
}
```

**Comment by thecavus** [comment] 2022-12-17 20:43
@dshukertjr  Hello, I understand that the problem is not related to the `cagriIstegi`.  I have this problem when I do any update or insert operation on the database.  I have not experienced this issue with 0.3.3

**Comment by dshukertjr** [comment] 2022-12-18 00:37
@thecavus 
Please provide the details so that we can reproduce the issue on our end and fix it. 

- What version of `postgrest` are you using? This can be found in your pubspec.lock file.
- What is the column type of `gelen_arama`? Is it `jsonb`?


I couldn't reproduce the issue with this where `json_column` is type of `jsonb`. Could you provide the raw string value and not variable for one example that will fail? .
```dart
await supabase.from('random').update({
  'json_column': {
      'cagriKodu': 'aaa',
      'arayanUid': 'bbb',
      'arananUid': 'ccc',
  }
}).eq('id', '11244617');
```

**Comment by dshukertjr** [comment] 2023-01-20 02:52
I'm going to close this issue for now, but please feel free to reopen it if the issue persists.

**Closed by dshukertjr** 2023-01-20 02:52 UTC
Labels: bug
