### ISSUE TITLE
Calling `signInWithIdToken()` to create a user throws an Internal Server Error

### ISSUE THREAD

**Issue by Ben1980** [supabase/supabase-flutter#578] opened 2023-08-02 12:28 UTC
signInWithIdToken() or signInWithApple() is only working if a user has been already created. How about a signup method for those providers within Supabase? some apps do provide full signup with providers, e.g. with Apple this is pretty common.
Currently, I get an `AuthException(message: Internal Server Error, statusCode: 400)` when trying to use an unregistered user.

**Comment by dshukertjr** [comment] 2023-08-03 01:13
@Ben1980 
Hmm, signInWithIdToken() and signInWithApple() should work with a user who doesn't have an account yet. Could you check your auth logs in your Supabase dashboard to see if you can find more details about the error?

**Comment by Ben1980** [comment] 2023-08-03 12:04
I have the following error in the logs:

```
Log ID
f6573897-f0f1-4a88-91c5-0c59dbcb121d

Log Timestamp (UTC)
2023-08-03T11:58:30.000Z

Log Event Message
{"component":"api","error":"500: Database error saving new user","level":"info","method":"POST","msg":"server_error: Internal Server Error","path":"/token","referer":"","remote_addr":"77.12.55.125","time":"2023-08-03T11:58:30Z","timestamp":"2023-08-03T11:58:30Z"}

Log Metadata
[
  {
    "message": null,
    "timestamp": "2023-08-03T11:58:30Z",
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "info",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "server_error: Internal Server Error",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-vqhkaytjsmznpkvlsvad",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": "/token",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [],
    "args": [],
    "referer": null,
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": "77.12.55.125",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": "500: Database error saving new user"
  }
]
```
And a warning:
```
Log ID
ca121f03-9a7c-4d04-94b1-d3c1dcea24e6

Log Timestamp (UTC)
2023-08-03T11:58:30.000Z

Log Event Message
{"component":"api","level":"warning","method":"POST","msg":"ID token has a at_hash claim, but no access_token parameter was provided. In future versions, access_token will be mandatory as it's security best practice.","path":"/token","referer":"","remote_addr":"77.12.55.125","time":"2023-08-03T11:58:30Z","timestamp":"2023-08-03T11:58:30Z"}

Log Metadata
[
  {
    "message": null,
    "timestamp": "2023-08-03T11:58:30Z",
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "warning",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "ID token has a at_hash claim, but no access_token parameter was provided. In future versions, access_token will be mandatory as it's security best practice.",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-vqhkaytjsmznpkvlsvad",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": "/token",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [],
    "args": [],
    "referer": null,
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": "77.12.55.125",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": null
  }
]
```

In addition I'm asking myself how I would provide additional data, e.g. a successful registration needs a username. With `signup()` this is no problem because I can pass the data:
```
final sb.AuthResponse res = await _auth.signUp(
        email: email,
        password: password,
        data: {'user_name': username},
        emailRedirectTo: 'com.octologs://auth/',
);
```
But with signInWithApple() or others I don't know how to provide this data.

**Comment by Ben1980** [comment] 2023-08-03 12:05
I think my last point is the root cause `"error": "500: Database error saving new user"` My database is expecting additional user data. how can I provide this data?

**Comment by dshukertjr** [comment] 2023-08-03 15:42
@Ben1980 Ah, you have a custom trigger on your auth.users table huh? In a case of third party provider login, the meta data gets populated with whatever comes back from the OAuth provider. I think you would have to modify your trigger function to make it compatible with both when a `username` is provided and when apple provided metadata is present. 

I'm going to close this issue as the we discovered that the original issue was not the issue caused by the SDK.

**Closed by dshukertjr** 2023-08-03 15:42 UTC
Labels: enhancement

**Comment by Ben1980** [comment] 2023-08-03 16:53
Thank you @dshukertjr, that's a good hint. Do you know any documentation on how to do this for Apple and Google? I'm new to this. Thats how my triggered function looks like
```
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, user_name)
  values (new.id, new.raw_user_meta_data->>'user_name');
  return new;
end;
$function$
;
```

**Comment by dshukertjr** [comment] 2023-08-04 15:48
@Ben1980 
Sorry, but at the moment we don't have any documentation on what meta data values appeal and Google login will populate. You could remove the trigger temporary, perform Apple, and Google login, and see the `raw_user_meta_data` column of `auth.users` table. Then, you could use a few if else statements within your `handle_new_user` function to pull in different meta data values into the user name.

**Comment by Tananga** [comment] 2024-09-12 19:50
@dshukertjr  I have exactly the same error but even If trigger is turned off I still see AuthException(message: Internal Server Error, statusCode: 400)
