### ISSUE TITLE
Flutter -  Storage createSignedUrl throws Object not found

### ISSUE THREAD

**Issue by darwin-morocho** [supabase/supabase-flutter#1051] opened 2024-10-01 11:20 UTC
**Describe the bug**
In flutter using `supabase_flutter: ^2.7.0` when I try to download a file from a private bucket I always get the next error

```
[log] StorageException (StorageException(message: Object not found, statusCode: 404, error: not_found))
[log] #0      Fetch._handleResponse (package:storage_client/src/fetch.dart:173:7)
```

**To Reproduce**
1. Create a new private bucket.
2. Add a bucket policy.
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/535c80ec-866e-4f8a-96de-2d8e74058924">
3. Upload a file
<img width="792" alt="image" src="https://github.com/user-attachments/assets/1bbf937c-a5a5-45a6-9260-4c034e724e98">

3. Get an URL
```dart
      final downloadUrl = await _client.storage.from('updates').createSignedUrl( 'admin/v1.3.5.apk', 300);
```

4. If you change change the bucket to public and use `getPublicUrl` function instead of `createSignedUrl` I am able to download the file.

**Expected behavior**
A valid URL string must be returned.

**Comment by dshukertjr** [comment] 2024-10-01 12:30
The cause is probably because the RLS policy evaluates to false for the user, so I would debug there. In the policy, you only allow the `private` folder to be accessible, but in the screenshot, you have an `admin` folder. 

Also, not critical, but if you have a target role set, you don't need `auth.role() = 'authenticated'` part.

**Comment by darwin-morocho** [comment] 2024-10-02 10:24
> The cause is probably because the RLS policy evaluates to false for the user, so I would debug there. In the policy, you only allow the `private` folder to be accessible, but in the screenshot and the sample code, you have an `admin` folder.
> 
> Also, not critical, but if you have a target role set, you don't need `auth.role() = 'authenticated'` part.

event adding files in the root file. I have the same problem

**Comment by dshukertjr** [comment] 2024-10-03 14:26
@darwin-morocho 
> event adding files in the root file. I have the same problem

Not entirely sure what you mean here, but currently you have `storage.foldername(name)[1] = 'private'::text` in your RLS, which means that only files in the `private` folder can be accessed. In your Dart code, you are trying to access the `admin` folder. 

I'm going to close this as the issue seems to be just a simple error, but do let us know if you still think it's an issue on the SDK.

**Closed by dshukertjr** 2024-10-03 14:26 UTC
Labels: bug, storage
