### ISSUE TITLE
Subscriptions listening to onAuthStateChange are not invoked when auto-login is performed after Supabase initialization.

### ISSUE THREAD

**Issue by UnRyongPark** [supabase/supabase-flutter#331] opened 2023-01-13 04:20 UTC
**Describe the bug**
When we try to handle authentication information, we may want to do a specific operation depending on whether we are logged in or not. (We are managing it as onAuthStateChange.)

However, since SupabaseAuth is initialized directly within the Supabase.initialize method, if there is a Persistent Session, login is performed immediately.

We can't register event listeners until Supabase.initialize has finished all the work, so we can't receive events no matter how soon we set listen to onAuthStateChange.

The steps that are executed are described below.

1. [user] Supabase.initialize call
2. [supabase] SupabaseAuth.invoking initialize
3. [supabase] persistented session up
4. [user] Register client.auth.onAuthStateChange event listening

**To Reproduce**
1. Write a code to listen to onAuthStateChange after Supabase.initialize according to the official document.
2. Launch the application and log in in in a normal way.
3. Exit the application and run it again to log in as a persistedSession session.
4. No signIn events are received.

**Expected behavior**
SignIn events must be received even when logged in as persistedSession session.

**Screenshots**

**Version (please complete the following information):**
1.2.2

**Additional context**

--

Currently, I am using it after simply modifying it after forking.(https://github.com/UnRyongPark/supabase-flutter)
Please let me know if there is a good way other than this.

**Comment by dshukertjr** [comment] 2023-01-13 04:32
@UnRyongPark 
It seems like you didn't add the Expected behavior, but what is the expected behavior here? If you want to know if a user is signed in or not at any point, you can use `supabase.auth.currentSession` to get the session. If session is null, the user is not signed in.

**Comment by UnRyongPark** [comment] 2023-01-13 04:44
@dshukertjr Hello :)
I modified the content.
What I want is to receive AuthChangeEvent.signedIn event when it is actually processed.

I want to manage the status in a separate state without looking up the status with `Supabase.instance.auth.currentUser` or  `supabase.auth.currentSession` every time.

**Comment by dshukertjr** [comment] 2023-01-13 05:01
@UnRyongPark 
Thanks for adding some context!

I have created a PR to solve this so that the listening to `supabase.auth.onAuthStateChanged` will emit the last event when listened to, which should be the behavior that you want!

I want to ask one question though, how are you checking if user is not signed in? If the user is signed in, there will be an event fired, but if the event doesn't fire, you wouldn't know if the user is not signed in or the signin event hasn't fired yet, right? Because of this, I still think you would have to check `currentState` at least to determine the initial auth state, but do you have a workaround?

**Comment by UnRyongPark** [comment] 2023-01-13 12:56
@dshukertjr 

Thank you.

As you thought, it is correct that we cannot verify 100% certain status without checking the `currentState`.

First of all, in my case, if the sign in event is not delivered, it is assumed to be in the Sign out state.

As you said, we made a process to check information at an irregular time, considering the situation where the event is not fired or the status event is not delivered for some reason.

For example, some navigation observers or some methods that look up user information include a hook to check `currentState`.
(If `currentState` cannot be retrieved, the Sign out event is forced to run.)

I don't think this is the best option, but I thought it would be difficult to manage it later if I manage the status through Supabase.instance in too many places (view, controller, observers etc.).

**Comment by dshukertjr** [comment] 2023-01-17 05:33
@UnRyongPark This should now be resolved with the newest version of gotrue-dart. Could you try running `flutter pub upgrade gotrue` and see if it behaves the way you wanted it to?

**Comment by UnRyongPark** [comment] 2023-01-17 12:22
@dshukertjr 
Sadly, I have bad news.
As you said, I upgraded Gotrue and used it, but the same phenomenon is happening.
In addition, I tried the latest version of the supabase_flutter, but the same situation occurs.

1. already logged in.
2. Close the app and run it again to access persisted session.
3. AuthChangeEvent.signed event is not invoked.

**Comment by dshukertjr** [comment] 2023-01-17 13:01
@UnRyongPark 
In step 3, do you see no events, or do you see no events being emitted?

Could you open `pubspec.lock` file and confirm that `gotrue` is v1.4.2?

**Comment by dshukertjr** [comment] 2023-01-20 02:19
@UnRyongPark 
I will close this issue for now, because the issue is fixed on my end, but feel free to reopen it if the issue persists on your end!

**Closed by dshukertjr** 2023-01-20 02:19 UTC
Labels: bug
