### ISSUE TITLE
supabase.auth.onAuthStateChange.listen not trigered

### ISSUE THREAD

**Issue by fastdao** [supabase/supabase-flutter#263] opened 2022-11-01 23:34 UTC
supabase.auth.onAuthStateChange.listen not trigered. Magic link went blank page when clicked

**Comment by dshukertjr** [comment] 2022-11-02 04:04
Hi @fastdao 

Sorry to hear that you are having some difficulties making onAuthStateChange work. Could you follow the issue template and provide some code that you are using along with some detailed explanations with steps to reproduce?

**Comment by fastdao** [comment] 2022-11-03 05:08
[image: image.png]  This is my storage policies for inserting files, and I
got storageexception(message new row violates row-level security policy for
table objects.
[image: image.png] And this is what I used to upload the avatars through
flutter.

**Comment by bohan0** [comment] 2022-11-03 19:27
What I have notice in both 1.0.1 and 1.1.0, is that the first login event (i.e. initial session/recovered session during app launch) is not fired. When I manually detect for the presence of a a initial session during app launch and fire the even manually, things work. Example below:

```
  ///When a user signs in, the subscribers are provided with ID & email address
  ///of the newly logged in user
  StreamSubscription subscribeToSignInEvent(
      void Function(String id, String email) loginCallback) {
    var s = _supabaseClient.auth.onAuthStateChange.listen((data) {
      final AuthChangeEvent event = data.event;
      if (event == AuthChangeEvent.signedIn) {
        loginCallback(_supabaseClient.auth.currentUser!.id, _signedInEmail);
      }
    });

    //manually trigger event for initial session recover during app launch
    //wordaround for superbase-flutter not firing the first onAutStateChange during app launch
    if (_supabaseClient.auth.currentSession != null) {
      loginCallback(_supabaseClient.auth.currentUser!.id, _signedInEmail);
    }

    return s;
  }
```

**Comment by bohan0** [comment] 2022-11-04 17:52
Regarding my above comment. I think this is a race condition type issue. Basically, the initial onAuthStateChange event may fired before the listening object has been created/attached, hence missing this first event.

You cannot attach the listener before Supabase.initialize() as that will result in an exception from supabase-flutter, so best choice is to check whether the user is logged in when the listener first attaches and do something appropriate (like navigate to a particular route). After this, you can depend on the onAuthStateChange for further changes in auth state.

**Comment by dshukertjr** [comment] 2022-11-17 04:16
>What I have noticed in both 1.0.1 and 1.1.0, is that the first login event (i.e. initial session/recovered session during app launch) is not fired

This is actually done so by design. At supabase, we thought firing `signedIn` event at the beginning when no sign in event has occurred was unintuitive, so we don't fire `signIn` event at the beginning. 

>You cannot attach the listener before Supabase.initialize() as that will result in an exception from supabase-flutter, so best choice is to check whether the user is logged in when the listener first attaches and do something appropriate (like navigate to a particular route). After this, you can depend on the onAuthStateChange for further changes in auth state (which may also include the first login if network is slow and the event triggers after your listener is attached).

Yup, thank you for an amazing summary. This is how exactly you should handle redirects depending on the auth state!

I would like to close this issue, but do let me know of any ideas on how we can make this more obvious to users. Maybe more comments docs?

**Closed by dshukertjr** 2022-11-17 04:16 UTC
Labels: bug
