### ISSUE TITLE
It is not possible to put more than one filter in real-time stream

### ISSUE THREAD

**Issue by codefutura** [supabase/supabase-flutter#857] opened 2024-03-11 14:04 UTC
**error when trying to add more than one filter in real-time stream**
example: supabase
         .from('tbl')
         .stream(primaryKey: ['id']).gte('created_at', dateInit)
           .lte('created_at', dateEnd)

**Comment by dshukertjr** [comment] 2024-03-12 05:00
Closing as duplicate of https://github.com/supabase/supabase-flutter/issues/338

**Closed by dshukertjr** 2024-03-12 05:00 UTC
Labels: enhancement, realtime

**Comment by codefutura** [comment] 2024-03-12 20:39
thank you
