### ISSUE TITLE
[Gotrue] client cannot login due to auth.currentSession being NULL

### ISSUE THREAD

**Issue by delfme** [supabase/supabase-flutter#662] opened 2023-10-08 16:58 UTC
If token is expired, Gotrue doesn't authenticate user (`auth.currentSession` is always returned null )
and issue doesn't resolve with subsequent requests.

I also filed a ticket coz initially I was thinking that the issue was affecting all clients due to maybe Gotrue server being down. Then I tried to run app from my second phone (with a different account) and discovered that issue was affecting only the previous account probably due to not refreshing session after token expiration. 

What is weird is that issue didnt resolve all day long. Cannot understand whether issue is caused by flutter plugin or Gotrue server itself.

Plugin version: ^1.10.21

To fix issue, had to delete account and signup.

**Comment by dshukertjr** [comment] 2023-10-08 23:43
Are you using email + password sin in? Perhaps is this account that you are experiencing this issue with is a brand new account that you just signed up with?

**Comment by delfme** [comment] 2023-10-09 05:39
Hello Tyler, thx for the kind attention.

We are using phone otp signup, so no pwds on signins.

Is refresh token managed automatically or must the client listen on auth to refreh token on expirations?
Coz as far as I can see, we are not refreshing token in our code. We just do:

```
static Session? get session => auth.currentSession;
```

As for your guess, indeed lately we also saw this very issue when doing a signup after account deletion, if user signups with the same phone number. No issue if user signups with a different phone number. But we are still investigating this to maybe open a separate issue, if needed. Do you think they might be intertwined?

**Comment by dshukertjr** [comment] 2023-10-09 05:51
@delfme 
>Is refresh token managed automatically or must the client listen on auth to refreh token on expirations?

Tokens are managed automatically. You do not need to manually refresh it or anything. 

Okay, let's step back a little. Since you skipped the issue template we provided, we don't have the necessary information to look into this issue. Could you provide detailed step-by-step instructions on how to reproduce the issue you are experiencing?

**Comment by delfme** [comment] 2023-10-09 06:24
Ops, my bad, filed this real quick from phone while travelling.
Will add missing info soon.

**Comment by delfme** [comment] 2023-10-09 06:43
Unfortunately we don't have a sample code for this and our app code is close.
But here is what we do:
```
...
static GoTrueClient get auth => Supabase.instance.client.auth;
static final authController = StreamController<AuthChangeEvent>.broadcast();
static Session? session;

static Future<void> initialize() async {
    await Supabase.initialize(
      url: _url,
      anonKey: _publicAnonKey,
      debug: kDebugMode, // optional
    );

  //Auth.currentSession is null when issue occurs
  debugPrint('$_debugPrefix Auth.currentSession is: ${auth.currentSession}'); 

   auth.onAuthStateChange.listen((data) async {
      debugPrint(
          '$_debugPrefix onAuthStateChange event is: ${auth.currentSession}');
      // Added this only lately, for testing
      if(data.event == AuthChangeEvent.tokenRefreshed){
       debugPrint('$_debugPrefix Token refreshed}'); 
        session = data.session;
      }
      if (data.event == AuthChangeEvent.signedIn) {
        session = data.session;
       ...
      // our code here
      }
      if (data.event == AuthChangeEvent.signedOut) {
        authController.add(data.event);
       // our code here
      }
    });

```

User is signed in via OTP Phone
```
  static Future<void> signInWithPhoneNumber({
    required String countryCode,
    required String number,
  }) async {
    final phone = '$countryCode$number'.trim();
    try {
      await auth.signInWithOtp(phone: phone);
      debugPrint('$_debugPrefix OTP send without issues to $phone');
    } on AuthException catch (error) {
      debugPrint(
          '$_debugPrefix Error sending OTP to $phone: ${error.message}');
    }
  }
```

**Comment by dshukertjr** [comment] 2023-10-09 07:11
@delfme 
What version of `supabase_flutter` were you using when the issue occurred, and do you experience it when you upgrade to the latest versions? 

Also, with the above code, do you lose sessions every single time when you perform a sign in and relaunch the app, or just once in a while?

**Comment by delfme** [comment] 2023-10-09 07:24
> @delfme What version of `supabase_flutter` were you using when the issue occurred, and do you experience it when you upgrade to the latest versions?

We were using `supabase_flutter: ^0.3.1+3` coz we had that issue of user being kicked off on token expiration and with that version issue looked mitigated. We then upgraded coz noticed the many improvements of the plugin since then.

However, issue was reproduced also on `supabase_flutter 1.10.21`, which made me wondering whether this might be a gotrue issue.

> 
> Also, with the above code, do you lose sessions every single time when you perform a sign in and relaunch the app, or just once in a while?

We lose session once in a while. Since we also refresh token once in a week, I linked the issue to token expiration, but maybe it is unrelated.

**Comment by dshukertjr** [comment] 2023-10-09 07:54
@delfme 
Okay, could you try this and see if you lose session if the app is not in production?

- Set the JWT expiration limit to 60 seconds on your Supabase dashboard
- Open the app
- Send OTP by calling `supabase.auth. signInWithOtp` method and providing a phone number
- Complete the sign in by calling `supabase.auth.verifyOtp` method and providing the phone number and the OTP
- Close the app
- Wait for a minute
- Open the app, and after walling `await Supabase.initialize()`, see if `supabase.auth.currentSession` still has non-null value

**Comment by delfme** [comment] 2023-10-09 10:42
Done. We get non null session / access token and access token is properly refreshed.
Tried 5 consecutive login.

**Comment by delfme** [comment] 2023-10-09 10:43
Since last time we just added this code where we set session on `AuthChangeEvent.tokenRefreshed`
```
 if(data.event == AuthChangeEvent.tokenRefreshed){
        //debugPrint('$_debugPrefix Token refreshed - session ${data.session}');
        session = data.session;
      }
```

**Comment by delfme** [comment] 2023-10-09 10:50
Indeed we still receive `PresenceAuth: Auth.currentSession is: null`.

**Comment by dshukertjr** [comment] 2023-10-09 11:02
@delfme 
Sorry, I am confused a bit. [Here](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752766816), you said that the session was non-null, and things were working fine, but you just mentioned [here](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752778426) that now the session is `null`. In your comment [here](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752778426), what are you logging? Are you logging the `session` variable that you initialized within your own code-base, or are you logging `Supabase.instance.client.auth.currentSession`?

Could you provide a step by step instruction similar to [what I provided](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752505974) so that we can reproduce what you are experiencing?

**Comment by delfme** [comment] 2023-10-09 11:12
Exactly, issue reverted and then occurred again out of blue. Now it works. It is like it occurs at times.

I print this log
```
  //Auth.currentSession is null when issue occurs
  debugPrint('$_debugPrefix Auth.currentSession is: ${auth.currentSession}'); 
```

Code is this one. Inside `initialize() ` we do `await Supabase.initialize()`, print log and listen on auth events.

```
...
static GoTrueClient get auth => Supabase.instance.client.auth;
static final authController = StreamController<AuthChangeEvent>.broadcast();
static Session? session;

static Future<void> initialize() async {
    await Supabase.initialize(
      url: _url,
      anonKey: _publicAnonKey,
      debug: kDebugMode, // optional
    );

  //Auth.currentSession is null when issue occurs
  debugPrint('$_debugPrefix Auth.currentSession is: ${auth.currentSession}'); 

   auth.onAuthStateChange.listen((data) async {
      debugPrint(
          '$_debugPrefix onAuthStateChange event is: ${auth.currentSession}');
      // Added this only lately, for testing
      if(data.event == AuthChangeEvent.tokenRefreshed){
       debugPrint('$_debugPrefix Token refreshed}'); 
        session = data.session;
      }
      if (data.event == AuthChangeEvent.signedIn) {
        session = data.session;
       ...
      // our code here
      }
      if (data.event == AuthChangeEvent.signedOut) {
        authController.add(data.event);
       // our code here
      }
    });
```

I will debug it a bit to try to see if I see a path in it. I will also test it on android to see if issue is crossplatform.

**Comment by delfme** [comment] 2023-10-09 12:32
To mitigate issue, would it be any helpful to add sth like?

```
// Force refreshSession on null
if (Supabase.instance.client.auth.currentSession != null) {
    await Supabase.instance.client.auth.refreshSession();
}
```

**Comment by dshukertjr** [comment] 2023-10-09 13:43
@delfme 
> To mitigate issue, would it be any helpful to add sth like?
>
>// Force refreshSession on null
>if (Supabase.instance.client.auth.currentSession != null) {
>    await Supabase.instance.client.auth.refreshSession();
>}

Did you try this code? It should just throw an error as you don't have a session.

To your knowledge, what is the rough probability in percent of this issue happening at any given app relaunch?

Also, could you modify your `onAuthStateChange` listener to include an `onError` handler to catch errors, and let me know if you observe any errors being printed?
```dart
auth.onAuthStateChange.listen((data) async {
  ...
    }).onError((error) {
      print('Error within onAuthStateChange: $error');
    });
```

**Comment by delfme** [comment] 2023-10-12 06:59
Hello @dshukertjr 
This just happened,  `Auth.currentSession is: null` and I was kicked off (I have to signup from scratch to login).
Ofc `Auth` is `Supabase.instance.client.auth`. 

Error is  `Invalid Refresh Token: Already Used`

```
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: Invalid Refresh Token: Already Used
flutter: #0      GotrueFetch.request (package:gotrue/src/fetch.dart:99:7)
flutter: <asynchronous suspension>
flutter: #1      GoTrueClient._callRefreshToken (package:gotrue/src/gotrue_client.dart:956:24)
flutter: <asynchronous suspension>
flutter: #2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:810:16)
flutter: <asynchronous suspension>
flutter: #3      SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:107:30)
flutter: <asynchronous suspension>
flutter: #4      Supabase.initialize (package:supabase_flutter/src/supabase.dart:102:5)
flutter: <asynchronous suspension>
flutter: #5      PresenceAuth.initialize (package:presence/api/auth.dart:66:5)
flutter: <asynchronous suspension>
flutter: #6      main (package:presence/main.dart:203:3)
flutter: <asynchronous suspension>
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
flutter: AuthException(message: Invalid Refresh Token: Already Used, statusCode: 400)
flutter: #0      GotrueFetch.request (package:gotrue/src/fetch.dart:99:7)
flutter: <asynchronous suspension>
flutter: #1      GoTrueClient._callRefreshToken (package:gotrue/src/gotrue_client.dart:956:24)
flutter: <asynchronous suspension>
flutter: #2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:810:16)
flutter: <asynchronous suspension>
flutter: #3      SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:107:30)
flutter: <asynchronous suspension>
flutter: #4      Supabase.initialize (package:supabase_flutter/src/supabase.dart:102:5)
flutter: <asynchronous suspension>
flutter: #5      PresenceAuth.initialize (package:presence/api/auth.dart:66:5)
flutter: <asynchronous suspension>
flutter: #6      main (package:presence/main.dart:203:3)
flutter: <asynchronous suspension>
flutter: PresenceAuth: Auth.currentSession is: null
flutter: PresenceAuth:  Error within onAuthStateChange: AuthException(message: Invalid Refresh Token: Already Used, statusCode: 400)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AuthException(message: Invalid Refresh Token: Already Used, statusCode: 400)
#0      GotrueFetch.request (package:gotrue/src/fetch.dart:99:7)
<asynchronous suspension>
#1      GoTrueClient._callRefreshToken (package:gotrue/src/gotrue_client.dart:956:24)
<asynchronous suspension>
#2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:810:16)
<asynchronous suspension>
#3      SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:107:30)
<asynchronous suspension>
#4      Supabase.initialize (package:supabase_flutter/src/supabase.dart:102:5)
<asynchronous suspension>
#5      PresenceAuth.initialize (package:presence/api/auth.dart:66:5)
<asynchronous suspension>
#6      main (package:presence/main.dart:203:3)
<asynchronous suspension>
```

**Comment by delfme** [comment] 2023-10-13 06:41
Kicked off again, first launch of the morning. 
Will track this for the next few days in order to also report frequency.

Still not sure whether this is client or Gotrue issue, coz error seems to be the token being already used. Is it the client generating the same uuid (flutter uuid plugin is bit buggy) or the server that expires the token before its expiration date (in that case the server will consider "already used" a token that is still the valid one) ?

**Comment by hf** [comment] 2023-10-13 10:36
This sort of error occurs because a refresh token (together in combination with the access token / JWT they make up the user's "session") is being used twice. A refresh token, generally speaking, must only be used once.

Usually this occurs when:

1. There's concurrent refresh of the session; avoid using the Supabase Auth library concurrently (this also means using it concurrently in promises too, not just in multi-threaded environments)
2. There was a failure to save the session right after it was refreshed, usually if the app is killed just after the refresh request was sent. To prevent this from happening, you should use a background task or service if possible so that the likelihood of the app being killed is very low.

Not sure if @dshukertjr has more information about specific Flutter issues that could help prevent those instances from occurring.

**Comment by iosephmagno** [comment] 2023-10-13 16:02
Hello @hf, thx for the kind attention.

@dshukertjr, as for point 2, if not already done, we could use `isolate` to run the background task, but wouldn't it be best if we also saved `refreshToken` and `lastUsedRefreshToken` to an Hive secure box (ie. `refreshTokensBox`) or to `flutter_secure_storage` and check them to avoid issue ?

@hf even if we adopt some smart logic to avoid point 1, can we also have a set of 10 `recoveryToken` that client can request to Gotrue server and use to recover from this problem? Those tokens are always usable as a valid token. When client runs out of `recoveryToken`, it can ask for another batch of 10 tokens to goTrue server. So, if shit happens we still have a recovery solution. Does it make sense?

**Comment by hf** [comment] 2023-10-17 09:37
@iosephmagno I fail to see how `recoveryToken` has anything to do with refresh tokens?

Please make sure to follow the guidelines I outlined above, as those are the best way to ensure that sessions don't get lost. We're working on making the algorithm in Supabase Auth a bit smarter about the issue when the client is unable to save the result, but this will be a few more weeks before it goes live.

**Comment by iosephmagno** [comment] 2023-10-17 14:28
> @iosephmagno I fail to see how `recoveryToken` has anything to do with refresh tokens?
> 
> Please make sure to follow the guidelines I outlined above, as those are the best way to ensure that sessions don't get lost. We're working on making the algorithm in Supabase Auth a bit smarter about the issue when the client is unable to save the result, but this will be a few more weeks before it goes live.

@hf idea was that clients gets `refreshToken` and `lastUsedRefreshToken` from box and if they are equal then will use a `recoveryToken` without making another call to grotrue to fetch a new one (to be faster).

> We're working on making the algorithm in Supabase Auth a bit smarter about the issue when the client is unable to save the result, but this will be a few more weeks before it goes live.

Thx for the effort! On mobile the situation is more extreme than web, if app kicks off users it will be trashed.

**Comment by dshukertjr** [comment] 2023-10-18 13:25
@iosephmagno 
>As for %, my reference is with the old plugin, Id say a few times a month, but we had jwt expiry set at 1ww. We had also an extra delay at app launch caused by await Supabase.initialize taking more time sometimes and that issue was more frequent. Will test the new situation during next week and lyk.

With the procedures outlined [here](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752505974), you were able to reproduce the session randomly being `null`, correct? When you are just testing it by yourself, roughly 1 in how many times does the session become `null` after reopening the app?

I want to say either of [these situations](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1761295414) is likely causing the session to be `null` in your case if you are able to reproduce the issue by just opening and closing the app on your phone quickly.

**Comment by delfme** [comment] 2023-10-18 13:50
> @iosephmagno
> 
> > As for %, my reference is with the old plugin, Id say a few times a month, but we had jwt expiry set at 1ww. We had also an extra delay at app launch caused by await Supabase.initialize taking more time sometimes and that issue was more frequent. Will test the new situation during next week and lyk.
> 
> With the procedures outlined [here](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1752505974), you were able to reproduce the session randomly being `null`, correct? When you are just testing it by yourself, roughly 1 in how many times does the session become `null` after reopening the app?

Hello @dshukertjr, yes, it was occurring often with 1m expiry, then I changed the expiry to 1hr and since then it has occurred 2-3 times. Didn't continue testing frequency more than so, coz in our case even one kickoff would be not bearable.

> I want to say either of [these situations](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1761295414) is likely causing the session to be `null` in your case if you are able to reproduce the issue by just opening and closing the app on your phone quickly.

Yea the points listed there seems to nail the root of the problem, coz we get the error of `Invalid Refresh Token: Already Used`. I suggested a quick workaround to avoid making the call with a duplicate token here https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1766537011 but I didnt look the code, just tried to share thoughts.

**Comment by dshukertjr** [comment] 2023-10-18 23:04
@delfme 
>it was occurring often with 1m expiry, then I changed the expiry to 1hr and since then it has occurred 2-3 times. Didn't continue testing frequency more than so, coz in our case even one kickoff would be not bearable.

And every time this session being `null` thing occurred you got `Invalid Refresh Token: Already Used` error, correct?

**Comment by delfme** [comment] 2023-10-19 08:38
@dshukertjr yes. Athough one time, before we were printing the error, user was not kicked off, yet couldnt pass login. I had to manually uninstall and re-install app to fix it. Idk if that is the signal of a second potential minor bug. It only occurred once.

**Comment by iosephmagno** [comment] 2023-10-26 22:00
@dshukertjr while waiting for the smarter flow, can we please try if this fix point 2
mentioned by @hf , if not already implemented? We use this to run some background heavy task in Presence. Please notice that `saveTokenFunction` must return Future<dynamic> even if it returns void.


```
Class {

// Call saveTokenFunction() to save token somewhere here
computeIsolate(saveTokenFunction(token));

}

// Top level functions
Future<dynamic> computeIsolate(Future<dynamic> function) async {
  final receivePort = ReceivePort();
  var rootToken = RootIsolateToken.instance!;
  await Isolate.spawn<_IsolateData>(
    _isolateEntry,
    _IsolateData(
      token: rootToken,
      function: await function,
      answerPort: receivePort.sendPort,
    ),
  );
  return await receivePort.first;
}

void _isolateEntry(_IsolateData isolateData) async {
  BackgroundIsolateBinaryMessenger.ensureInitialized(isolateData.token);
  final answer = await isolateData.function();
  isolateData.answerPort.send(answer);
}
class _IsolateData {
  final RootIsolateToken token;
  final Function function;
  final SendPort answerPort;

  _IsolateData({
    required this.token,
    required this.function,
    required this.answerPort,
  });
}

// Top level function coz we run it with isolate
Future<dynamic> saveTokenFunction (dynamic value) async {
  // your code here      
}
```

**Comment by iosephmagno** [comment] 2023-10-26 22:15
@hf as for the smarter flow, if the `recoveryTokens` approach doesnt look good, what about asking client to pass old seasion tokens?

I mean, in case of duplicate refresh token, server could let the client call a different endpoint to recover from this situation. Like, for example, client might pass to server the latest 3 valid used tokens, and if they are correct, the server will authenticate it. 

Just sharing thoughts.

**Comment by dshukertjr** [comment] 2023-10-30 21:02
@iosephmagno 
> while waiting for the smarter flow, can we please try if this fix point 2
mentioned by hf , if not already implemented?

Yeah, let me look into it.

**Comment by delfme** [comment] 2023-11-15 19:34
@dshukertjr @hf hello guys! Any news about this?
We are still pre-launch and dont panic on this but we will be ready soon and cannot ship app if that is not fixed. Any extra effort on this would be much apprecated.

Also, have you got the chance to investigate the ideas shared above?

**Comment by dshukertjr** [comment] 2023-11-16 13:42
@delfme 
Would you be able to try out the v2.0 developer preview version of supabase_flutter like this in pubspec.yaml? I have been unable to reproduce the loss of session with it. 

```yaml
supabase_flutter: ^2.0.0-dev.2
```

**Comment by delfme** [comment] 2023-11-16 16:03
Thx @dshukertjr will have a look at it and revert.
But is it just a clientside improvement or you got to add a recovery strategy to gotrue server. Coz last time I checked it looked like if auth goes wrong on client, it cannot recover from there.

**Comment by dshukertjr** [comment] 2023-11-17 03:56
@delfme 
There has been no server side changes, but there is one auth setting that you could tweak if you would like. 

Currently, when the client tries to refresh the access token and fails because of network or other issues, there is an 10 second (by default) window at which the same access token can be used to retrieve a new one. The client automatically retries to refresh the access token, and if it reaches the server within the 10-second window, it will successfully obtain a new session. You can increase this 10-second time window by going to  Refresh token reuse interval under
 `Settings -> Authentication -> Advanced -> Refresh Tokens`.  However, you would have to understand that this would come with a cost of sacrificing security, so please use caution when tweaking this number. Our recommendation is to leave it at 10 seconds. 

<img width="1056" alt="Screenshot 2023-11-17 at 12 26 04" src="https://github.com/supabase/supabase-flutter/assets/18113850/4914fc98-9acf-460d-909a-adf1c95f592a">

There is always a slim chance of [these events](https://github.com/supabase/supabase-flutter/issues/662#issuecomment-1761295414) happening, for any auth providers, and there is not much we can do without sacrificing security. 

I'm going to close this issue as there isn't much we can do to further improve the library regarding the issue.

**Closed by dshukertjr** 2023-11-17 03:56 UTC
Labels: bug, auth

**Comment by delfme** [comment] 2023-11-17 07:41
Yea the 10sec settings is the correct one.
But without an improvement on the server it is highly risky to ship a mobile app under current situation.

Lets make an example taking Whatsapp as reference and describing the scenario. What it might occur is that user wakes up, opens Whatsapp and either:
1) app is stuck at splash screen
2) user is kicked off from app and see the very first onbording screen where he is asked to signin with a new otp code

In case 1, user must delete app, download it back again, signup and go through a Restore Backup procedure that would restore maybe GB of data. That is pretty dramatic flow.

In case 2, user must signin with otp and will access again the app with its data but that would look scary (they would fear to have lost their chats history) and it is a very bad event in general.

Gotrue must provide supabase clients with a recovery strategy. I mentioned some above that are pretty safe. Please discuss it internally and let us know, coz we cannot ship app with the risk described above. Also, please let me know if we should submit a new ticket from supabase console to describe the situation. I recall @hf mentioned they were going to add a smart recovery strategy in a few weeks but he didnt update on that.

**Comment by delfme** [comment] 2023-11-17 08:34
1. Indeed, relauncing would fix this case most times, but once I personally had to uninstall and install app back. 
2. This is why recovery strategy is implemented in Auth providers :) By no chance users can get kicked off from any top-tier app, but I never experience this issue even with low-end apps.

As for 2) there are a few known strategies that could be adopted, some leverage on client sending to server a few backupped old tokens which respect a specific path. For example, imagine client calling a different api where to send the refresh token + 3 old access tokens which respect a specif rule. That’s pretty secure.

But whatever strategy that works, would be a good one.

**Comment by dshukertjr** [comment] 2023-11-17 08:42
@delfme 
Again, please discuss server side strategies on the gotrue repo. 
https://github.com/supabase/gotrue/issues
