### ISSUE TITLE
A problem occurred configuring project ':sign_in_with_apple'.

### ISSUE THREAD

**Issue by malakm2002** [supabase/supabase-flutter#537] opened 2023-07-08 09:18 UTC
**Describe the bug**
When trying to build the apk of my flutter project, I'm getting the below error: 
```
A problem occurred configuring project ':sign_in_with_apple'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

```
**Expected behavior**
I expected to have a successful build of the apk in order to release it on app center using the CI/CD of codemagic

**Version (please complete the following information):*

running:  `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` 
output:
```
supabase_flutter 1.10.6
    ├── supabase 1.9.5
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.9.0
    │   ├── postgrest 1.3.2
    │   ├── realtime_client 1.1.1
    │   ├── storage_client 1.5.1
```

**Comment by Vinzent03** [comment] 2023-07-08 09:26
Please share your whole error message.

**Comment by malakm2002** [comment] 2023-07-08 09:30
command on windows: flutter build apk

output:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sign_in_with_apple'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...                            3.6s
Gradle task assembleRelease failed with exit code 1
```

**Comment by Vinzent03** [comment] 2023-07-08 09:43
Well, have you tried what the error message asks you to do?

**Comment by malakm2002** [comment] 2023-07-08 12:40
I tried to but there is no file specific to the mentioned package for mw to add the namespace android.



Best Regards,
Malak



-------- Original message --------
From: Vinzent ***@***.***>
Date: 7/8/23 12:43 PM (GMT+02:00)
To: supabase/supabase-flutter ***@***.***>
Cc: "Malak Mehrez (Student)" ***@***.***>, Author ***@***.***>
Subject: Re: [supabase/supabase-flutter] A problem occurred configuring project ':sign_in_with_apple'. (Issue #537)


Well, have you tried what the error message asks you to do?

**Comment by Vinzent03** [comment] 2023-07-08 12:45
You should edit your own flutter app specific `android/app/build.gradle` file.

**Comment by malakm2002** [comment] 2023-07-08 13:15
it's already so:
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    namespace 'com.example.justice_accelerator'
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        applicationId "com.example.justice_accelerator"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
flutter {
    source '../..'
}


```

and the namespace matches the package name in the `Android_manifest.xml file`

**Comment by Vinzent03** [comment] 2023-07-08 13:37
That's strange. Maybe try running `flutter clean` and build again.

**Comment by malakm2002** [comment] 2023-07-08 13:46
Yes it's quite strange. I did and still gettthe same error.



Best Regards,
Malak



-------- Original message --------
From: Vinzent ***@***.***>
Date: 7/8/23 4:37 PM (GMT+02:00)
To: supabase/supabase-flutter ***@***.***>
Cc: "Malak Mehrez (Student)" ***@***.***>, Author ***@***.***>
Subject: Re: [supabase/supabase-flutter] A problem occurred configuring project ':sign_in_with_apple'. (Issue #537)


That's strange. Maybe try running flutter clean and build again.

**Comment by malakm2002** [comment] 2023-07-12 12:42
i am trying to run my flutter project and I am getting the below error:
```
Resolving dependencies...
  file 6.1.4 (7.0.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  sign_in_with_apple 4.3.0 (5.0.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.6.1 available)
Got dependencies!
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/sign_in_with_apple.dart:1:1: Error: Error when reading '../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple_platform_interface-1.0.0/lib/sign_in_with_apple_platform_interface.dart': The system cannot find the path specified.

export 'package:sign_in_with_apple_platform_interface/sign_in_with_apple_platform_interface.dart'
^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:6:8: Error: Error when reading '../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple_platform_interface-1.0.0/lib/sign_in_with_apple_platform_interface.dart': The system cannot find the path specified.

import 'package:sign_in_with_apple_platform_interface/sign_in_with_apple_platform_interface.dart';
       ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:5:8: Error: Error when reading '../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple_platform_interface-1.0.0/lib/method_channel_sign_in_with_apple.dart': The system cannot find the path specified.

import 'package:sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart';
       ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:54:17: Error: Type 'AuthorizationCredentialAppleID' not found.
  static Future<AuthorizationCredentialAppleID> getAppleIDCredential({
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:55:19: Error: Type 'AppleIDAuthorizationScopes' not found.
    required List<AppleIDAuthorizationScopes> scopes,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:60:5: Error: Type 'WebAuthenticationOptions' not found.
    WebAuthenticationOptions? webAuthenticationOptions,
    ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:92:17: Error: Type 'CredentialState' not found.
  static Future<CredentialState> getCredentialState(
                ^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:103:17: Error: Type 'AuthorizationCredentialPassword' not found.
  static Future<AuthorizationCredentialPassword> getKeychainCredential() async {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/supabase_flutter-1.10.8/lib/src/supabase_auth.dart:391:9: Error: The getter 'AppleIDAuthorizationScopes' isn't defined for the class 'GoTrueClient'.
 - 'GoTrueClient' is from 'package:gotrue/src/gotrue_client.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/gotrue-1.11.0/lib/src/gotrue_client.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'AppleIDAuthorizationScopes'.
        AppleIDAuthorizationScopes.email,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/supabase_flutter-1.10.8/lib/src/supabase_auth.dart:392:9: Error: The getter 'AppleIDAuthorizationScopes' isn't defined for the class 'GoTrueClient'.
 - 'GoTrueClient' is from 'package:gotrue/src/gotrue_client.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/gotrue-1.11.0/lib/src/gotrue_client.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'AppleIDAuthorizationScopes'.
        AppleIDAuthorizationScopes.fullName,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:13:8: Error: Undefined name 'SignInWithApplePlatform'.
      (SignInWithApplePlatform.instance as MethodChannelSignInWithApple)
       ^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:13:44: Error: 'MethodChannelSignInWithApple' isn't a type.
      (SignInWithApplePlatform.instance as MethodChannelSignInWithApple)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:29:12: Error: Undefined name 'SignInWithApplePlatform'.
    return SignInWithApplePlatform.instance.isAvailable();
           ^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:55:19: Error: 'AppleIDAuthorizationScopes' isn't a type.
    required List<AppleIDAuthorizationScopes> scopes,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:60:5: Error: 'WebAuthenticationOptions' isn't a type.
    WebAuthenticationOptions? webAuthenticationOptions,
    ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:74:12: Error: Undefined name 'SignInWithApplePlatform'.
    return SignInWithApplePlatform.instance.getAppleIDCredential(
           ^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:95:12: Error: Undefined name 'SignInWithApplePlatform'.
    return SignInWithApplePlatform.instance.getCredentialState(userIdentifier);
           ^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/sign_in_with_apple-4.3.0/lib/src/sign_in_with_apple.dart:104:12: Error: Undefined name 'SignInWithApplePlatform'.
    return SignInWithApplePlatform.instance.getKeychainCredential();
           ^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```
as I mentioned before, sign_in_with_apple is a subpackage of supabase_flutter package and I am not even using it in anything in my project

**Comment by malakm2002** [comment] 2023-07-12 18:02
@dshukertjr  thanks for your response! it was quite helpful!!

i ran the command `flutter build apk` but the error failed after 1 hour of running, giving the following error:

```
e: C:/Users/Malak/.gradle/caches/transforms-3/06f2116f8be11196a7a19c728bc85d67/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.    
e: C:/Users/Malak/.gradle/caches/transforms-3/06f2116f8be11196a7a19c728bc85d67/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.    
e: C:/Users/Malak/.gradle/caches/transforms-3/06f2116f8be11196a7a19c728bc85d67/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Malak/.gradle/caches/transforms-3/3800cb655c81a05fbca274220287b1b1/transformed/jetified-kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-std
lib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Malak/.gradle/caches/transforms-3/6acc6e0863171ff7107ee7df559058c0/transformed/jetified-annotation-jvm-1.6.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
```
i ran flutter clean, deleted the build file and the .gradle folder in android, and change the kotlin version to what is expected, and delete the caches folder from c/users/user_name/.gradle/ BUT still getting the same problem

**Comment by dshukertjr** [comment] 2023-07-13 05:40
@malakm2002 
Nice to see that there is progress!

So I'm assuming you have done all the steps described [here](https://stackoverflow.com/questions/67699823/module-was-compiled-with-an-incompatible-version-of-kotlin-the-binary-version-o#:~:text=Although%20this%20question%20has%20been%20answered%2C%20I%20think%20it%27s%20worth%20explaining%20what%20is%20happening) and you have `ext.kotlin_version = '1.8.0'` in your build.gradle file?

Rather than trying to find what is wrong within the `android` folder, what I typically do is just delete the entire `android` folder and recreate it with `flutter create .` command as I have suggested [here](https://github.com/supabase/supabase-flutter/issues/537#issuecomment-1632535190), but have you tried it?

**Comment by malakm2002** [comment] 2023-07-13 10:13
@dshukertjr 

appreciate your response!

yes, I've done them but apparently, the kotlin version and Gradle version were not compatible, so I fixed the compatibility issue. and this is my build.gradle file now.

```
buildscript {
    ext.kotlin_version = '1.8.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

also, I deleted the entire `android` folder and recreated it with `flutter create .`
and now, I'm back to the original problem: 
```
* What went wrong:
A problem occurred configuring project ':sign_in_with_apple'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }
```

**Comment by dshukertjr** [comment] 2023-07-13 12:50
@malakm2002 
You were right all along. Sorry to cause you all this trouble. I think I found the cause of it: https://github.com/flutter/flutter/issues/126403

We will ship a fix ASAP. Thanks for bearing with us!

**Comment by malakm2002** [comment] 2023-07-13 12:56
Dear @dshukertjr, I do really appreciate your efforts.

 i just would like to know if it will work anytime soon since I have to release the application by the end of this month.

**Comment by dshukertjr** [comment] 2023-07-13 13:15
@malakm2002 
We will release a new version as soon as https://github.com/supabase/supabase-flutter/pull/548 is merged, which should be within the next 24 hours at the very latest.

**Closed** 2023-07-13 13:27 UTC
Labels: bug

**Comment by malakm2002** [comment] 2023-07-13 13:29
@dshukertjr so what is the next step so that I can fix this problem?

**Comment by dshukertjr** [comment] 2023-07-13 13:41
@malakm2002 
supabase_flutter v1.10.9 was just published right now. Could you try to upgrade the package and see if you still get the same errors?

**Comment by Vinzent03** [comment] 2023-07-13 14:30
Please do the following:
1. remove the `sign_in_with_apple` dependency, as it's already contained in `supabase_flutter`
2. upgrade your flutter version to the latest hotfix `3.10.6`
3. upgrade all your packages via `flutter pub upgrade` and verify in `pubspec.lock` that you are using `sign_in_with_apple` v`5.0.0`
3. remove your android folder
4. Recreate it via `flutter create .`
5. Rebuild your app

That hopefully works

**Comment by malakm2002** [comment] 2023-07-14 11:20
@Vinzent03 

it solved the initial problem but now I have the following:

` C:/Users/Malak/.gradle/caches/transforms-3/fd083bb856d4a97482111f8d10eb4408/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

and this is my build.gradle file:

```
buildscript {
    ext.kotlin_version = '1.6.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```
a suggested flutter fix is to let the kotlin version be the latest which is 1.9.0 but it's not supported by my IDE: android studio so I put it as 1.8.22

kindly note that even when having 1.6.0 I'm still getting the problem.

**Comment by Vinzent03** [comment] 2023-07-14 13:04
I get a very similar error message, but for me it still outputs an apk and installs fine on my device. [This flutter issue](https://github.com/flutter/flutter/issues/130412#issuecomment-1635363490) might be the solution, but upgrading gradle breaks [url_launcher](https://github.com/flutter/packages/pull/4249). So I would just ignore that issue for now.

**Comment by malakm2002** [comment] 2023-07-15 04:04
I do agree and this is what happened when I upgraded gradle to 8.0.2 but the problem is that it is not building an apk

**Comment by dshukertjr** [comment] 2023-07-15 13:57
@malakm2002 
I would suggest opening an issue on the [Flutter repo](https://github.com/flutter/flutter/issues) about this one.

**Comment by bug-author** [comment] 2023-07-23 11:41
Same issue, using `supabase_flutter: ^1.10.9`.

**Comment by NaserAlt** [comment] 2024-12-12 17:50
bump

**Comment by Vinzent03** [comment] 2024-12-12 21:08
@NaserAlt This is not an issue with this package itself, but the dependency `sign_in_with_apple` or flutter itself so there is nothing we can do.
