### ISSUE TITLE
Explicit type cast UUID : text

### ISSUE THREAD

**Issue by stha-ums** [supabase/supabase-flutter#337] opened 2023-01-20 10:07 UTC
I have a table `user_setting` with the column name `user_id` of the type UUID which is the foreign key of the table `user`. When I query user_setting like this. 

```dart
final data = await Supabase.instance.client.from('user_setting')
        .select()
        .match({"user_id": "<UUID>"});
```

I get this type error
```
PostgrestException(message: operator does not exist: uuid = text, code: 42883, details: , hint: No operator matches the given name and argument types. You might need to add explicit type casts.)
```
Is there any way I can cast `user_id` as `UUID`?

**Comment by dshukertjr** [comment] 2023-01-20 13:50
@stha-ums 
You don't need to type cast it actually. This error occurs when the string that you are passing is not actually a UUID. Make sure the variable you are passing actually is not null or is a proper uuid format. 

```dart
assert(userId != null);
final data = await Supabase.instance.client.from('user_setting')
        .select()
        .match({"user_id": userId});
```

**Comment by dshukertjr** [comment] 2023-01-23 09:49
I will close this issue for now as the cause should be passing a none-uuid format string or null value to the API, but if this issue persists, feel free to reopen it and let us know!

**Closed by dshukertjr** 2023-01-23 09:49 UTC
Labels: bug
