### ISSUE TITLE
Local sync storage feature

### ISSUE THREAD

**Issue by cmedamine** [supabase/supabase-flutter#290] opened 2022-11-26 21:50 UTC
I'm trying to built an app that stores data on mobile and also syncs data in the cloud currently I have to do this manually, could supabase have sync feature in the future?

**Comment by dshukertjr** [comment] 2022-11-27 08:02
@cmedamine 
Kind of line [this](https://github.com/supabase/supabase-flutter/issues/140)?

**Comment by cmedamine** [comment] 2022-11-28 12:37
@dshukertjr  maybe but I mean using Sqlite in for local DB since Supabase use Postgres,

**Comment by dshukertjr** [comment] 2022-11-29 01:04
@cmedamine 
Thanks for confirming. If we would to implement something like that, it would most likely be using Sqlite. We do have plans working on this feature, but are taking some time with the reasons explained [here](https://github.com/supabase/supabase-flutter/issues/140#issuecomment-1180288706).

Will close this one as a duplicate of https://github.com/supabase/supabase-flutter/issues/140

**Closed by dshukertjr** 2022-11-29 01:04 UTC
Labels: enhancement
