### ISSUE TITLE
Error while txt or json uploading to supabase Strorage; ```Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.  - 'File/*1*/' is from 'dart:io'.```

### ISSUE THREAD

**Issue by BALU2000-creator** [supabase/supabase-flutter#715] opened 2023-11-18 12:20 UTC
Error in 43 line, at onPressed(), I'm trying to getting the file example.txt using File() and passing it to upload function in myWidget class,
```
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:universal_io/io.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
    url: 'Supabase_url',
    anonKey: 'AnonKey'
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: MyWidget(),
    );
  }
}

final supabase = Supabase.instance.client;

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () {
        final file = File('example.txt');
        file.writeAsStringSync('File content');
        supabase.storage
            .from('myBucket')
            .upload('my/path/to/files/example.txt', file);
      },
      child: const Text('Upload'),
    );
  }
}


```
In the above example, I'm trying to upload a .txt file to Supabase storage. However, I encountered an error in the process.

```
lib/main.dart:41:53: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:storage_client/src/file_stub.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/storage_client-1.5.4/lib/src/file_stub.dart').
            .upload('my/path/to/files/example.txt', file);
```

Please provide the solution for this,
Thank you.

**Comment by DanMossa** [comment] 2023-11-18 16:22
Duplicate of https://github.com/supabase/supabase-flutter/issues/685

**Closed** 2023-11-18 16:23 UTC
Labels: bug
